### ISSUE TITLE
Support HPKP

### ISSUE THREAD

**Issue by bax-** [lukas2511/dehydrated#129]
I would be a great addition if this script also pu out something which could be used in HKPK headers, e.g. with hooks.
For an example see
https://calomel.org/lets_encrypt_client.html

**Comment by lukas2511** [comment]
You should be able to do that inside the deploy_cert hook. I don't really see any benefit of having this directly inside of this script.

**Comment by bax-** [comment]
Accepted.
I'll try to learn how to do this.

**Comment by bax-** [comment]
This is what I'm trying out at the moment.
I have yet to find out how to automatically replace the parts in my server config though…

```
#!/bin/bash

function deploy_cert {
    local DOMAIN="${1}" KEYFILE="${2}" CERTFILE="${3}" CHAINFILE="${4}"
    hpkp="$(openssl rsa -in ${BASEDIR}/certs/${DOMAIN}/privkey.pem -outform der -pubout 2>/dev/null | openssl dgst -sha256 -binary | openssl enc -base64)"
  printf "\nHTTP Key Pinning\n   pin-sha256=\"$hpkp\";\n"
}

HANDLER=$1; shift; $HANDLER $@
```

**Comment by germeier** [comment]
Shouldn't an include directive do the trick? This way you only need to generate a file with the HKPK config.

**Comment by bax-** [comment]
yes, that might be a good idea!
https://github.com/lukas2511/letsencrypt.sh/issues/131

**Comment by bax-** [comment]
How about having an option in the config and making this a part of lets encrypt.sh?
add a file with the HKPK hash for embedding it somewhere with a hook!

**Comment by lukas2511** [comment]
And create that file in every config format for every webserver out there? No thanks.

**Comment by bax-** [comment]
The hash is the same, it is just different for RSA and ECDSA certificates.

**Comment by lukas2511** [comment]
The config file format for every webserver out there is different. 
If this would be a feature I'd either have to decide on which servers to support or support them all. 
A few config-syntax examples are listed in the url you posted in the first message of this conversation:

```
## apache configuration
Header set public-key-pins "pin-sha256=\"FdFOH8lP8ipUaas4cnj92Ifk81feECxL/RGDps3otfw=\"; pin-sha256=\"LeSTjTfnibfKHJmDfIGoWrE7JwFWMUy/+3Ft55sBTGs=\"; max-age=604800; includeSubDomains"

## nginx configuration
add_header public-key-pins 'pin-sha256="FdFOH8lP8ipUaas4cnj92Ifk81feECxL/RGDps3otfw="; pin-sha256="LeSTjTfnibfKHJmDfIGoWrE7JwFWMUy/+3Ft55sBTGs="; max-age=604800; includeSubDomains';

## h2o configuration
header.add: "public-key-pins: pin-sha256=\"FdFOH8lP8ipUaas4cnj92Ifk81feECxL/RGDps3otfw=\"; pin-sha256=\"LeSTjTfnibfKHJmDfIGoWrE7JwFWMUy/+3Ft55sBTGs=\"; max-age=604800; includeSubDomains"
```

You should easily be able to do that for your specific webserver configuration in a hook script, but this will never be a feature of this script.

**Comment by bax-** [comment]
I thought just about the hash, not the whole header implementation.
`FdFOH8lP8ipUaas4cnj92Ifk81feECxL/RGDps3otfw=`
Then it could be included in the server config dynamically or manipulated with a script.

**Comment by lukas2511** [comment]
Just use hook scripts... doing it this way just makes everything a lot more complicated.

**Comment by bax-** [comment]
OK.
I just thought it would be nice to have a file symlinking to the latest version, just like the keys and the certificates. Thought it might be helpful for others as well.

**Comment by bax-** [comment]
I'm still pursuing this.

I would need to have `${KEY_ALGO}` and `${timestamp}` passed to the hook for this to work.
Or it could become integrated into letsencrypt.sh and become an option.

Depending on which option you would prefer I would try to make a pull request.

This is what I have so far:

```
echo " + Generating HPKP information..."

case "${KEY_ALGO}" in
      rsa) hpkp="$(_openssl rsa -in ${KEYFILE} -outform der -pubout 2>/dev/null | openssl dgst -sha256 -binary | openssl enc -base64)"
      prime256v1|secp384r1) hpkp="$(_openssl ec -in ${KEYFILE} -outform der -pubout 2>/dev/null | openssl dgst -sha256 -binary | openssl enc -base64)"
    esac
         
echo $hpkp >> "${BASEDIR}/certs/${DOMAIN}/hpkp-${timestamp}.txt"
ln -sf "${BASEDIR}/certs/${DOMAIN}/hpkp-${timestamp}.txt" "${BASEDIR}/certs/${DOMAIN}/hpkp.txt"
```

**Comment by lukas2511** [comment]
creating a textfile like this would be okay.

on the deploy_cert hook i'd then like to just have the timestamp added, so that it can be used for future features and we don't need to add more options all the time.

**Comment by lukas2511** [comment]
This should be doable in the `deploy_cert` hook by now, everything that is needed for generating those config entries is exported and there even is support for key rollover now, making this actually useful.

**Comment by vi** [comment]
<s>Maybe there should be a mode with fixed private key and CSR to have a permanent pin?

Like with `--signcsr` mode, but employing `/var/lib/dehydrated/certs/` structure (with `privkey.pem` and `cert.csr` as regular files, not symlinks)?
</s>

Maybe the `PRIVATE_KEY_RENEW` config options should be better advertised/documented?

**Comment by txr13** [comment]
@vi Was having that option written up in the `config` file (which is linked to from the readme) not sufficient?

**Comment by vi** [comment]
I don't see it in the [README](https://github.com/lukas2511/dehydrated/blob/master/README.md).

I discovered it from the source code after already deploying `--signcsr`-based scheme.

**Comment by txr13** [comment]
From `README.md`:
> Have a look at docs/examples/config to get started, copy it to e.g. /etc/dehydrated/config and edit it to fit your needs.

From `docs/examples/config`:
>#Regenerate private keys instead of just signing new certificates on renewal (default: yes)
>#PRIVATE_KEY_RENEW="yes"

**Comment by vi** [comment]
Yes, now I found.
