### ISSUE TITLE
rename certificates with status 409 already revoked to .pem-revoked

### ISSUE THREAD

**Issue by gertcuykens** [lukas2511/dehydrated#236]
Currently `./letsencrypt.sh -r cert.pem` does not rename certificates that are already revoked by a ohter client.

Suggest to also rename with `.pem-revoked` them when you get the following error.

```
Revoking ..
  + ERROR: An error occurred while sending post-request to https://acme-staging.api.letsencrypt.org/acme/revoke-cert (Status 409)

Details:
{
  "type": "urn:acme:error:malformed",
  "detail": "Certificate already revoked",
  "status": 409
}
```

**Comment by lukas2511** [comment]
Yes, this is because the error message isn't (yet) parsed in any way, and without any knowledge on why revocation failed it doesn't make sense to move certificates around.
