### ISSUE TITLE
Feature: Account update

### ISSUE THREAD

**Issue by gertcuykens** [lukas2511/dehydrated#239]
Commands:
--account (-a) Update contact information

https://ietf-wg-acme.github.io/acme/#registration

For example, to update the contact information in the above registration, the client could send the following request:

```
POST /acme/reg/asdf HTTP/1.1
Host: example.com

/* BEGIN JWS-signed request body */
{
  "resource": "reg",
  "contact": [
    "mailto:certificates@example.com",
    "tel:+12125551212"
  ],
}
/* END JWS-signed request body */
```

**Comment by lukas2511** [comment]
This feature is now implemented, thanks to @lukavia!
