### ISSUE TITLE
Feature Request: Registering account key with letsencrypt without requesting domain 

### ISSUE THREAD

**Issue by philkunz** [lukas2511/dehydrated#246]
Since the account key is the only component that is written by all parallel processes requesting a domain initially when not present, it would be cool if one could request it synchronously without having to specify a domain.

(the sync/async handling is handled by the calling script of cause and has nothing to do with letsencrypt.sh itself)

**Comment by lukas2511** [comment]
I just implemented `--register` in 6a32f20e004b9d835cd02de9d78300be02784cf1
