### ISSUE TITLE
Do not hard code subscriber agreement URL

### ISSUE THREAD

**Issue by rolandshoemaker** [lukas2511/dehydrated#249]
Boulder provides the current subscriber Agreement in a `Link` header of the type `terms-of-service` in response to a valid `/acme/new-reg` POST request, this should be used instead of hard coding the most recent URL.

Continuing to hard code the URL will cause consistent failures for anyone trying to create a new registration whenever Let's Encrypt chooses to update their agreement.

**Comment by Celti** [comment]
AFAIK, the reason for the current “hard-coding” (it's not hard-coded, it's a variable adjustable in the config file) is that that in theory provides a fool-proof method of demonstrating you agree with the current terms of service.

I don't think it should be automatically drawn from the headers — but perhaps it would be smart for letsencrypt.sh to include logic that informs you “The terms of service have updated; here is the link to the Subscriber Agreement. Please update your configuration to agree with the new terms.”

**Comment by pcfreak30** [comment]
Just added support for this in vestacp.
You can use the following command to get the agreement url `agreement=$(curl -s -I "$api/terms" |grep Location |cut -f 2 -d \ |tr -d '\r\n')` with `$api` being `api='https://acme-v01.api.letsencrypt.org'`

**Comment by lukas2511** [comment]
Closing in favor of #346, thanks for your hints.
