### ISSUE TITLE
OpenSolaris (Joyent) Compatibility

### ISSUE THREAD

**Issue by EvilJordan** [lukas2511/dehydrated#255]
The flag "grep -A1" on line 412 is not supported in Open Solaris.
If you have SANs, this will be a problem.

Therefore, a simple change can be made and then everything works without a hitch!
I wasn't sure how best to submit this, so I'm just doing it here in the hopes anyone Googling for an answer will find it.

Change:
`altnames="$( <<<"${reqtext}" grep -A1 '^[[:space:]]*X509v3 Subject Alternative Name:[[:space:]]*$' | tail -n1 )"`
to:
`altnames="$( <<<"${reqtext}" awk '/^[[:space:]]*X509v3 Subject Alternative Name:[[:space:]]*$/{print;getline;print;}' | tail -n1 )"`

**Comment by to-kn** [comment]
Hi, on Debian with
`awk -W version
mawk 1.3.3 Nov 1996, Copyright (C) Michael D. Brennan

compiled limits:
max NF             32767
sprintf buffer      2040
`
this break things and it always exits with "ERROR: Certificate signing request contains non-DNS Subject Alternative Names"

**Comment by lukas2511** [comment]
@to-kn thanks, this should be fixed now

**Comment by to-kn** [comment]
Hi @lukas2511 no, i think you missunderstood me - the change you made (changing to awk instead of grep) does not work at the mentioned system...

**Comment by txr13** [comment]
This is the same error as reported in #351. Apparently installing gawk fixed the error--perhaps different providers of awk yield different results?

**Comment by lukas2511** [comment]
@to-kn i did unterstand that, i was able to reproduce it using mawk, i changed how awk is used in this case and it should work with mawk now too, please test the change i made in 3d8d320c9f5a8dbd2621de28cd02f8ba15be5dbf

**Comment by EvilJordan** [comment]
Sorry to have caused so much trouble, guys. Is there a way to force gawk use over grep at the command line?
