### ISSUE TITLE
Responding to challenge fails with "Provided key authorization was incorrect"

### ISSUE THREAD

**Issue by virgoparna** [lukas2511/dehydrated#268]
I'm trying to use letsencrypt.sh to generate certificates, but I'm getting an error always. 
I initially used Debian packaged version, but I then also tried the version from git.
Error is:

ERROR: An error occurred while sending post-request to https://acme-v01.api.letsencrypt.org/acme/challenge/CENSORED/CENCORED (Status 400)
Details:
{
  "type": "urn:acme:error:malformed",
  "detail": "Unable to update challenge :: Provided key authorization was incorrect",
  "status": 400
}

**Comment by virgoparna** [comment]
And Apache logs show no attempt to access ".well-known/acme-challenge"

**Comment by virgoparna** [comment]
Since I got it working with official cerbot client I will not be able to do additional verification. Just for information.

**Comment by lukas2511** [comment]
Not sure what was causing this, closing this ticket since it seemed to be a one-off issue.
