### ISSUE TITLE
RSA key 4096

### ISSUE THREAD

**Issue by venigo** [lukas2511/dehydrated#276]
Howto set all certs on 4096 to get a better score?

I run the script like ./letsencrypt.sh -c

The output:

> 1	Sent by server	
Fingerprint SHA1: 1bc48b413fb0fd446161f284050ee7d955a2c13d
Pin SHA256: 8d4OB2KT3OBcUvgs8BiZrqjPhNyozJNNBBexbQ0Q9MA= 
RSA 4096 bits (e 65537)	/ SHA256withRSA
2	Sent by server	Let's Encrypt Authority X3 
Fingerprint SHA1: e6a3b45b062d509b3382282d196efe97d5956ccb
Pin SHA256: YLh1dUR9y6Kja30RrAn7JKnbQG/uEtLMkBgFF2Fuihg= 
RSA 2048 bits (e 65537)	/ SHA256withRSA
3	In trust store	DST Root CA X3   Self-signed	
Fingerprint SHA1: dac9024f54d8f6df94935fb1732638ca6ad77c13
Pin SHA256: Vjs8r4z+80wjNcr1YKepWQboSIRi63WsWXhIMN+eWys= 
RSA 2048 bits (e 65537)	/ SHA1withRSA 
Weak or insecure signature, but no impact on root certificate

**Comment by lukas2511** [comment]
The certificates generated by this script are using 4096 bit RSA keys by default, the 2048 bit key ist the root CA key which was generated by Let's Encrypt.

**Comment by venigo** [comment]
Thank you for the reply,

So how can I fix this (not an expert user).
Remove the 2 2048 bit ca keys? How?

2016-09-15 10:43 GMT+02:00 Lukas Schauer <notifications@github.com>:

**Comment by venigo** [comment]
Is it in the sh script..

Is it possible to add --rsa-key-size 4096?

**Comment by minagerges** [comment]
@venigo , there is no further action required from your side or this repository owner, everything is working as it should and as you expect.
You can not change anything related to the intermediate cert or ca cert.
Google is your friend to get more knowledge on digital certs.
