### ISSUE TITLE
letsencrypt.sh/dehydrated: line 80: unexpected argument `(' to conditional binary operator

### ISSUE THREAD

**Issue by kayyazka** [lukas2511/dehydrated#284]
Hi, 

I have problem on this line 

letsencrypt.sh/dehydrated: line 80: unexpected argument `(' to conditional binary operator

And i change argument with add "" in (http-01|dns-01)

from :
[[ "${CHALLENGETYPE}" =~ (http-01|dns-01) ]] || _exiterr "Unknown challenge type ${CHALLENGETYPE}... can not continue."

to :
[[ "${CHALLENGETYPE}" =~ "(http-01|dns-01)" ]] || _exiterr "Unknown challenge type ${CHALLENGETYPE}... can not continue."

after that. i run  ./letsencrypt.sh --config /etc/pki/config.sh --cron
and i get error 

ERROR: Challenge is invalid! (returned: invalid) (result: {
  "type": "http-01",
  "status": "invalid",
  "error": {
    "type": "urn:acme:error:unauthorized",

Additional information:
cat /proc/version
Linux version 2.6.18-8.el5 (brewbuilder@ls20-bc2-14.build.redhat.com) (gcc version 4.1.1 20070105 (Red Hat 4.1.1-52)) #1 SMP Fri Jan 26 14:15:21 EST 2007

uname -a
Linux  2.6.18-8.el5 #1 SMP Fri Jan 26 14:15:21 EST 2007 i686 i686 i386 GNU/Linux

cat /etc/*release
Red Hat Enterprise Linux Server release 5 (Tikanga)

what should i do to fix it?

Thank you in advance

**Comment by kayyazka** [comment]
I have update new script but still error like it

**Comment by lukas2511** [comment]
Uff... support for linux distributions from the stone age...

You could try deleting the accounts directory, maybe there just is a broken account key, but I have a feeling that if this one line results in a problem some others might too...

I'll leave this open for now, but keeping compatibility with bash versions from probably over ten years ago is definitively not something I want to spend too much time on.

**Comment by lukas2511** [comment]
Not going to fix this, sorry.
I'd suggest trying to update your version of Bash, or better: Update your whole OS, does that thing even get security updates anymore?...
