### ISSUE TITLE
Fails on busybox

### ISSUE THREAD

**Issue by paour** [lukas2511/dehydrated#285]
Busybox systems have an implementation of `tr` that doesn't support classes, so `tr '[:upper:]' '[:lower:]'` doesn't do what the script expects.

[This stackexchange page](http://unix.stackexchange.com/a/136132) lists some alternative implementation suitable for Busybox.

**Comment by paour** [comment]
With this change and a deploy_cert hook to change the certs to DER format, dehydrated works fine on openwrt, thanks!

**Comment by lukas2511** [comment]
Interesting, I'll have a look at this, would be cool to have support on some embedded devices.

**Comment by abelbeck** [comment]
@paour with our somewhat old BusyBox v1.19.4 this works:
```
# echo 'RoadRunner' | tr '[:upper:]' '[:lower:]'
roadrunner
```
There is a BusyBox configuration option:
```
CONFIG_FEATURE_TR_CLASSES=y
```
```
config FEATURE_TR_CLASSES
   bool "Enable character classes (such as [:upper:])"
   default y
   depends on TR
   help
     Enable character classes, enabling commands such as:
     tr [:upper:] [:lower:] to convert input into lowercase.
```

@lukas2511 Though using Busybox the ```-u``` option for ```mktemp``` is not supported, this solves the test for mktemp:
```
-   _mktemp -u > /dev/null 2>&1 || _exiterr "This script requires mktemp."
+   which mktemp > /dev/null 2>&1 || _exiterr "This script requires mktemp."
```
Possibly you could use ```which``` to test for all command dependencies.

**Comment by lukas2511** [comment]
I just pushed a few changes and dehydrated now works fine under OpenWrt after installing bash, openssl-util and diffutils.
