### ISSUE TITLE
Feature Request: Delayed Certificate Symlinking

### ISSUE THREAD

**Issue by ggiesen** [lukas2511/dehydrated#288]
Would it be possible to implement the ability to delay symlinking to the new cert for x days/invocations/etc to allow time to update TLSA records before the cert is made active.

Perhaps create a new symlink when the cert is created (such as fullchain-new.pem/chain-new.pem/cert-new.pem) which would give a good way for the tlsa script to grab the hash, and then after x invocations or days pull the symlink and re-symlink fullchain.pem to the new cert.

**Comment by rohieb** [comment]
I was also thinking about this, exactly for the same reason. But I think this is already possible with a hook script. In this case, I would not let my web server use the cert directly from `$BASEDIR/certs/$DOMAIN/`, but from a different location. The hook script then creates an entry in `/etc/cron.d` that waits for the TLSA record TTL to run out, and then copies the certificate to the new location and restarts the web server.

**Comment by ggiesen** [comment]
Yeah that'd certainly work, but would require a separate hook script for each service. I was trying to keep the hook script generic (well, specific to the DNS server, but generic in terms of the service it's supporting).

**Comment by lukas2511** [comment]
Mh, I don't think this has a good place in this script so I'm closing this issue.

What will be coming (hopefully kinda soonish) is private key rollover for use with HPKP, would this maybe also solve the problem with TLSA records?

**Comment by alainwolf** [comment]
There can be more then one TLSA record in DNS. Add the new one, but don't delete the old existing one.
You then delete expired TLSA entries by a separate cron-job, by reading the "Not-Valid-Before" date of the new cert and it is more then 2x the DNS records TTL in the past. Or you read the old certs "Not-Valid-After" date and delete that TLSA record, when its in the past.
