### ISSUE TITLE
Error while trying to get cert on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by PeterDaveHello** [lukas2511/dehydrated#290]
Sorry that I'm not sure if this is a problem of dehydrated, it only appear on one of my servers with Ubuntu 16.04 LTS, and the error message is very not help.

Tried v2.0~3.1, same version and same parameters can work on one another server.

Here is the error message:

```
# INFO: Using main config file /etc/letsencrypt.sh/config.sh
  + ERROR: An error occurred while sending get-request to https://acme-v01.api.letsencrypt.org/directory (Status 403)

Details:
<HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>

You don't have permission to access "http&#58;&#47;&#47;acme&#45;v01&#46;api&#46;letsencrypt&#46;org&#47;directory" on this server.<P>
Reference&#32;&#35;18&#46;75481160&#46;1475353435&#46;800eb1b
</BODY>
</HTML>
```

I tried to use a browser to see the message, I got this

```
Access Denied

You don't have permission to access "http://acme-staging.api.letsencrypt.org/" on this server.
Reference #18.75481160.1475352241.7fbb713
```

Googled (also duckduckgo) 18.75481160.1475352241.7fbb713 but got nothing, have no idea about how to do to debug this problem, any suggest will be appriaciated, thanks!

**Comment by adduxa** [comment]
It seems like you tried to get access to ACME server via http instead of https (CA variable in config file)

**Comment by PeterDaveHello** [comment]
@adduxa I thought the part you mentioned is just a mistake from the error message returned from ACME server, the CA variable in the script is 100% https no problem, and as I say, the same same script, different 3 versions, run on my two different server, got two different result.

**Comment by adduxa** [comment]
Oh.. Ok, this is strange

**Comment by ccjon** [comment]
It's been a few weeks since did this on Ubuntu 16.04 LTS and it worked. But I recall having similar issues until I got the correct CA files, and particularly the Intermed. CA. I was using Let’s Encrypt Authority X1 which is retired: X3 is current.

**Comment by lukas2511** [comment]
Not sure what was going on here, but it seems to me that Let's Encrypt just locked you out for some reason, this doesn't seem to have anything to do with dehydrated.
