### ISSUE TITLE
Create PEM-file combining certificate and key

### ISSUE THREAD

**Issue by tinloaf** [lukas2511/dehydrated#295]
Hi,

dehydrated already very handily creates the chain-PEMs, but e.g. lighttpd[0] requires a PEM file that's a combination of the key and the certificate. Would it be possible to also create that? I could probably do that through a hook, but that seems kind of bothersome..

Thanks a lot,
Lukas

[0] http://redmine.lighttpd.net/projects/lighttpd/wiki/Docs_SSL

**Comment by lukas2511** [comment]
See example hook script section `deploy_cert`, it should be very easy to just `cat` those files together and even reload lighttpd when it's done.
