### ISSUE TITLE
Requesting certificates can hang if a challenge is not required to do so

### ISSUE THREAD

**Issue by aaronmdjones** [lukas2511/dehydrated#297]
Please see https://community.letsencrypt.org/t/challenges-stay-at-pending-state-acme-client-locks-up/21188/ for a description of the problem and a possible solution.

**Comment by txr13** [comment]
I'm pretty sure this was addressed by #293 (and #321), as dehydrated now checks for existing domain validations.

**Comment by lukas2511** [comment]
I also think this is fixed now, feel free to comment if this is still an issue.
