### ISSUE TITLE
create certificate in --out(put) while using --signcsr

### ISSUE THREAD

**Issue by broedli** [lukas2511/dehydrated#303]
Hi,
I'm trying to automate my renewal for certificates with hkpk / dane in mind (using --singcsr /path/to/my.csr --out /path/to/location) but only get the cert as an output in shell. Am I missing something or is this not supported?

**Comment by lukas2511** [comment]
The `--out` parameter is only used for normal operation.

When you are signing a CSR you have to handle everything else yourself, the script only does the validation and asks Let's Encrypt to sign your CSR.
