### ISSUE TITLE
Add support for appending custom EC/DH parameters

### ISSUE THREAD

**Issue by lumag** [lukas2511/dehydrated#304]
According to [mod_ssl documentation](https://httpd.apache.org/docs/2.4/mod/mod_ssl.html#sslcertificatefile) it is possible to instruct Apache2 to use custom DH parameters or EC curve by appending that data to first certificate specified by `SSLCertificateFile`. Please add support for adding such data. Thanks!

**Comment by leonklingele** [comment]
Why not use the dedicated Apache directives for doing that?
You can specify the curve to use for ECDH via: `SSLOpenSSLConfCmd ECDHParameters [curve-name]`
and specify the parameters for DH via: `SSLOpenSSLConfCmd DHParameters /path/to/dhparams.pem`

**Comment by lumag** [comment]
This directive is not available with OpenSSL < 1.0.2 (and that is not the case e.g. for Debian Jessie).

**Comment by welwood08** [comment]
This is already possible using the deploy_cert hook. Just append what you need to the cert file before you deploy it to apache.
