### ISSUE TITLE
CRON example

### ISSUE THREAD

**Issue by almereyda** [lukas2511/dehydrated#306]
I am creating new certificates with `$ vim /root/renew.sh`

```
#!/bin/sh

/root/github.com/lukas2511/dehydrated/dehydrated -c
/usr/sbin/nginx -t && /usr/sbin/nginx -s reload
```

and `$ crontab -e`

```
@daily /root/renew.sh
```

Should we add such a sample to the documentation?

**Comment by lukas2511** [comment]
You could also reload nginx in a hook script and just use `dehydrated -c` in the cron, no need to write a wrapper script.

**Comment by almereyda** [comment]
Thank you, yes, this is what I was missing.

**Comment by TyrfingMjolnir** [comment]
```
crontab -l www
55 23 * * * /opt/local/dehydrated/dehydrated -c; svcadm refresh nginx
```
