### ISSUE TITLE
Is it possible to obtain challenges without verification?

### ISSUE THREAD

**Issue by porunov** [lukas2511/dehydrated#312]
Hello,

Is it possible to obtain challenges without verification and after that execute dehydrated again to verify domain?
Unfortunately I can't execute script on the server. But I can place any files manually under "http://mydomain.com/.well-known/acme-challenge/something". It would be great to be able obtain challenges and verify domain with another command.

Sincerely,
Alexandr

**Comment by leonklingele** [comment]
https://github.com/lukas2511/dehydrated/issues/138 might be of help

**Comment by porunov** [comment]
Unfortunately I can't create an account with that script because of this issue: https://github.com/gheift/letsencrypt.sh/issues/24

**Comment by lukas2511** [comment]
You can use `deploy_challenge` and `clean_challenge` hooks to upload and delete challenges to your web-server via FTP or something similar.
