### ISSUE TITLE
Does the DNS update hook need to be run for subsequent verifications after the first verification in DNS mode?

### ISSUE THREAD

**Issue by sudoman** [lukas2511/dehydrated#313]
I didn't find this information in your documentation, but from what I can gather, the presence of the plethora of hooks suggests that automation is necessary because each month or two, full DNS verification with hooks is necessary when verifying in DNS mode.

Is this correct? Thanks!

**Comment by whereisaaron** [comment]
Whether you use HTTP or DNS verification, Let's Encrypt certificates are valid for only 90 days. So you have to automate re-verifying and issuing new certificates every couple months, plus deploying the new certs to any service that uses them, and restarting the service if necessary.

**Comment by sudoman** [comment]
Thanks, that clarifies. I wasn't sure whether a static DNS config could be used for later verification.
