### ISSUE TITLE
does dehydrated support domain verification by https(port 443)

### ISSUE THREAD

**Issue by barsara** [lukas2511/dehydrated#315]
Hi 

As what we know, http and dns is used to verify domain owner in common.
But our customer site block http(port 80) and they don't have right or skill to modify dns record, the only chance for us to verify domain owner is https(port 443).

Does dehydrated support domain verification by https(port 443), like letsencrytp-auto 
--standalone-supported-challenges http-01 to use port 80
--standalone-supported-challenges tls-sni-01 to use port 443

Thank in advance~

**Comment by lukas2511** [comment]
Not yet, sorry.

**Comment by waja** [comment]
This a duplicate of #271
