### ISSUE TITLE
IDNs support

### ISSUE THREAD

**Issue by Louvremaster** [lukas2511/dehydrated#317]
Hello!

Let’s Encrypt now supports issuance for Internationalized Domain Names (IDNs) (https://letsencrypt.org/upcoming-features/). Please add IDNs support for your script.

Thanks

**Comment by lukas2511** [comment]
If they don't work out of the box I won't add support for them, unicode is hard and it's way too easy to make mistakes, especially when systems are using different versions of the tools with different localization.

If i understand this correctly you can still use the ascii "punycode" representation of the domain and it should work anyway.
