### ISSUE TITLE
Feature request: specifying alternative domains.txt file

### ISSUE THREAD

**Issue by aijanai** [lukas2511/dehydrated#332]
Hey,

first of all, thanks for this great script.

I have some domains on CloudFlare and others on Route53. This forces me to rotate the file domains.txt to use different hooks.

It would be nice if I could just specify as a parameter the right domains.txt file

**Comment by lukas2511** [comment]
That is already implemented, see `docs/examples/config`:

```
# File containing the list of domains to request certificates for (default: $BASEDIR/domains.txt)
#DOMAINS_TXT="${BASEDIR}/domains.txt"
```

Another option would be to call dehydrated using `dehydrated -d your.domain -d www.your.domain` to directly sign certain domains instead of using domains.txt for that.

**Comment by aijanai** [comment]
great, let's make it more visible in the client help :)
