### ISSUE TITLE
What can I do about Weak Diffie-Hellman and the Logjam Attack

### ISSUE THREAD

**Issue by maxisme** [lukas2511/dehydrated#333]
What can I do about [this](https://weakdh.org/)?

I ran https://www.ssllabs.com/ssltest/analyze.html on a domain with the certificates generated by `dehydrated`. 

And the NGINX config:

```
server {
        listen 443 ssl;

        server_name                 notifi.it;

        root /var/www/notifi.it/public_html;
        index index.php index.html index.htm;

        ssl on;
        ssl_certificate             /etc/nginx/certs/notifi.it/fullchain.pem;
        ssl_certificate_key         /etc/nginx/certs/notifi.it/privkey.pem;

        error_page 404 /404.html;

        location / {
                try_files $uri $uri/ @extensionless-php;
        }

        location @extensionless-php {
            rewrite ^(.*)$ $1.php last;
        }

        location ~ \.php$ {
                try_files $uri =404;
                fastcgi_pass unix:/var/run/php5-fpm.sock;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;

        }
}
```

And I got a B because of the key exchange:

> This server supports weak Diffie-Hellman (DH) key exchange parameters

**Comment by dorelo** [comment]
Consider generating stronger DH parameters than Nginx's default 1024 bits.

`openssl dhparam -out /etc/nginx/dhparam.pem 2048`
then add the line
`ssl_dhparam /etc/nginx/dhparam.pem;` to your nginx config(s).

It is possible to up the size to 4096 bits, 2048 is a generally safe size.

**Comment by maxisme** [comment]
http://pasteboard.co/1OvuYl1Pf.png
