### ISSUE TITLE
challenge tokens are created in wrong directory for freeBSD

### ISSUE THREAD

**Issue by tekbasse** [lukas2511/dehydrated#335]
challenge tokens are created in WELLKNOWN dir instead of WELLKNOWN/.well-known/acme-challenge/

for bash under freeBSD 10.3  See #334 

After commenting out line 545:
` [[ "${CHALLENGETYPE}" = "http-01" ]] && rm -f "${WELLKNOWN}/${challenge_token}"`

The files are found in WELLKNOWN dir.

**Comment by lukas2511** [comment]
This is not a bug, this is a feature: https://github.com/lukas2511/dehydrated/blob/master/docs/wellknown.md

**Comment by tekbasse** [comment]
I call it a documentation bug. Poorly explained.

**Comment by lukas2511** [comment]
In that document I state multiple times how files are stored, and there even is example configuration for probably every popular webserver, I'm really not sure what else I can do.

If you have a suggestion on how to make the documentation better feel free to send in a pull-request.

**Comment by tekbasse** [comment]
Okay. Will do.

**Comment by tekbasse** [comment]
The acme standard requires the file to be served from /.well-known/acme-challenge/

> The path at which the resource is provisioned is comprised of the fixed prefix
".well-known/acme-challenge/", followed by the "token" value in the challenge.
The value of the resource MUST be the ASCII representation of the key
authorization.

`.well-known/acme-challenge/evaGxfADs6pSRb2LAv9IZf17Dt3juxGJ-PCt92wr-oA`

from: [https://github.com/ietf-wg-acme/acme/blob/master/draft-ietf-acme-acme.md](url)

So, WELLKNOWN needs to include this fixed value at the end.

The pull request will reflect this description.

cheers, Ben
