### ISSUE TITLE
ERROR: Error when trying to get nonce

### ISSUE THREAD

**Issue by Sparc0** [lukas2511/dehydrated#337]
When i try to sign my cert i get following error. Anyone had the same problem?

INFO: Using main config file /opt/certificate/dehydrated/config
Processing hackernet.se
 + Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till Jan  8 05:33:00 2017 GMT (Less than 30 days). Renewing!
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting challenge for hackernet.se...
ERROR: Error when trying to get nonce

**Comment by lukas2511** [comment]
Are you using hook scripts? "Error when trying to get nonce" is not an error message of dehydrated but after just googling it I found it's an error of `pdns-client`. I'm closing this ticket as it's not an issue with dehydrated itself.
