### ISSUE TITLE
Add --no-ocsp command line option

### ISSUE THREAD

**Issue by alainwolf** [lukas2511/dehydrated#338]
In my config files I set `OCSP_MUST_STAPLE="yes"`.

I'm already juggling with a multiple config files for different use cases (i.e. to create RSA and EC keys in different cert directories).

But now a subset of my hosts can't have `OCSP_MUST_STAPLE`. Either the server software does not support it (e.g. mail servers), or there are other hosts outside of my control, which wont support it.
If added in a configuration file, the number of config files and cron-tasks needed grows exponentially.

If I could leave it on by default in my configs, but set it off for a small subset of hosts by command-line would be a great. 

Thank you for your consideration and your awesome script. Have a nice day.

**Comment by lukas2511** [comment]
See https://github.com/lukas2511/dehydrated/blob/master/docs/per-certificate-config.md, this should help you.

**Comment by txr13** [comment]
@lukas2511

Given that the request was for a command-line flag to unset the MUST_STAPLE option,  and given that there's already a flag which essentially sets MUST_STAPLE at execution time, would it not be feasible to implement a flag to unset at execution time? (Read and process the config file, then process script arguments to set / unset the needed option, abort with error if both --ocsp and --no-ocsp are given as arguments.)

If I better understood how to properly fork a branch and submit a PR, I'd do that...

**Comment by lukas2511** [comment]
@txr13 i don't want to overload the script with switches, i think that just makes it more complicated to use
