### ISSUE TITLE
account argument

### ISSUE THREAD

**Issue by chriddyp** [lukas2511/dehydrated#341]
Is it possible to specify your account ID as an input argument? In cerbot, it's:

```
  --account ACCOUNT_ID  Account ID to use (default: None)
```

(See http://letsencrypt.readthedocs.io/en/latest/using.html)

For more info about the use case for account IDs, see "One Account or Many?" here: https://letsencrypt.org/docs/integration-guide/

Thanks a bunch!

**Comment by txr13** [comment]
`dehydrated` supports the `--privkey` option for this use case.

**Comment by chriddyp** [comment]
Got it. Thank you!
