### ISSUE TITLE
make a v0.3.2 release?

### ISSUE THREAD

**Issue by ThomasWaldmann** [lukas2511/dehydrated#342]
I use dehydrated from git checkout and ran into the issue that v0.3.1 checkout does not work for alternate names with dns authentication, like:

```
example.org www.example.org
```

So I currently have to checkout / use master to get it working (the issue was fixed after v0.3.1).

As dehydrated installation is automated via ansible, I had to pin the current commit hash to have it reproducable - which is a bit unpretty.

I also imagine a lot of people just installing via pip run into this issue and not everybody wants to use the git version, so a new release would be nice.

**Comment by lukas2511** [comment]
This is weird, I can't remember fixing anything like that after the v0.3.1 release, do you know which commit solved your problem?

Anyway... A new version will be released soon(ish), I'm getting back into the mood of working on this project and I want to get rid of a few older issues first.

**Comment by ThomasWaldmann** [comment]
No, I didn't bisect it. I just couldn't get it working with 0.3.1, then upgraded to tip, then it worked.

**Comment by ThomasWaldmann** [comment]
Just guessing, maybe that one?:

https://github.com/lukas2511/dehydrated/commit/9729751d93b59d9bef2347406716e4a593cf8dee

**Comment by lukas2511** [comment]
If that is what "solved" your issue you may run into trouble soon, the only change with that is that it skips verification if that already happened for each altname.

**Comment by lukas2511** [comment]
v0.4.0 released :)

**Comment by ThomasWaldmann** [comment]
\o/
