### ISSUE TITLE
Releases: Please provide signatures

### ISSUE THREAD

**Issue by ge-fa** [lukas2511/dehydrated#345]
Would it be possible for you, to provide signatures for the releases, so one is able to ensure the pulled in code, for example into Debian, wasn't tampered with along the way? [Here](https://wiki.debian.org/Creating%20signed%20GitHub%20releases) is a small guide how to do this.
Thanks!

**Comment by lukas2511** [comment]
I've signed the latest release and from now on I'll sign all my commits using `3C2F2605E078A1E18F4793909C4DBE6CF438F333`, but I can't promise to remember to always upload a signature when I release a new version.

**Comment by ge-fa** [comment]
Thanks, that's great! To make it easier to remember this, if case you're using some sort of a script to do the release, maybe it would be good to incorporate this inside there.

**Comment by lukas2511** [comment]
My workflow is to just tag a specific commit and copy the changelog to the release, if you know of any way to completely automate this I'm open for suggestions.

**Comment by ge-fa** [comment]
Ah yeah, I see. Not sure how this could work with the "automatic" releases provided by GitHub. Maybe something like [this](https://github.com/aktau/github-release) could be of any help.
