### ISSUE TITLE
Better license handling

### ISSUE THREAD

**Issue by lukas2511** [lukas2511/dehydrated#346]
Currently users are basically accepting the Let's Encrypt terms of service the moment they run dehydrated for the first time, this is a bit ugly and since it's missing any hint on that it may not even be fully legal...

To make this better dehydrated should query boulder for the required license url and ask the user to set this URL in config on first use.
This way everything can still be fully automated by just adding the LICENSE variable to the configuration file, but for normal use it will make the user aware of the terms of service.

This ticket replaces #249 and #248.

**Comment by lukas2511** [comment]
Implemented in 6a32f20e004b9d835cd02de9d78300be02784cf1

**Comment by ezbik** [comment]
So basically when they set new license URL in some monthes, what are steps to update automated setups? Manually update `$LICENSE` in `config` ? Or nothing is required?

**Comment by lukas2511** [comment]
Until now License only seems to be verified on registration, not entirely sure if there is some kind of account-update for future license changes, I'll have to look into that, but otherwise nothing is required to be changed.

**Comment by cpu** [comment]
> Until now License only seems to be verified on registration, not entirely sure if there is some kind of account-update for future license changes

The agreement URL is only enforced at the time of registration creation. The wording of the terms-of-service is such that existing accounts are automatically agreed to future updates without needing to do any kind of account update for the new ToS if it changes.
