### ISSUE TITLE
Feature proposal: Intermediate certificates cache

### ISSUE THREAD

**Issue by rpv-tomsk** [lukas2511/dehydrated#353]
The walk_chain() requests certificates from remote server each time.
It can use local certificate copy instead.

Algo:

1) Get certificate issuer hash 

`ISSUER_HASH="$($OPENSSL x509 -in "${CERT}" -noout -issuer_hash)"`

2) Check if we already have its local copy in cache

3) If have, use it, if no - download and store to cache (filename is formed as `${ISSUER_HASH}.crt`).

The similar is implemented in https://github.com/matteocorti/check_ssl_cert/commit/cf368d3b71dc787c8449aae90d177efdc6d042a9 

Although that is much more important there in monitoring (it requested much more often than in renewal process).

What do you think about this feature?

Thanks for your tool.

**Comment by lukas2511** [comment]
Implemented in d685463673919ba4f9d2035d021293f241a66055, thanks for the suggestion.
