### ISSUE TITLE
Allow otherNames Aliases

### ISSUE THREAD

**Issue by kermitDerFrosch** [lukas2511/dehydrated#356]
Use this diff to allow signing of working xmpp s2s certs.

[others.diff.txt](https://github.com/lukas2511/dehydrated/files/783140/others.diff.txt)

**Comment by lukas2511** [comment]
I don't understand, where does this `othername:` come from? The only thing I found that mentioned this was for arbitrary data which doesn't really make sense for altnames...

**Comment by kermitDerFrosch** [comment]
you need something like this, for correct s2s support

```
subjectAltName = @subject_alternative_name

[subject_alternative_name]
DNS.0 = <yourdomain>
DNS.1 = conference.<yourdomain>
DNS.2 = proxy.<yourdomain>
otherName.0 = 1.3.6.1.5.5.7.8.7;IA5STRING:_xmpp-client.<yourdomain>
otherName.1 = 1.3.6.1.5.5.7.8.7;IA5STRING:_xmpp-server.<yourdomain>
otherName.2 = 1.3.6.1.5.5.7.8.5;FORMAT:UTF8,UTF8:<yourdomain>
otherName.3 = 1.3.6.1.5.5.7.8.5;FORMAT:UTF8,UTF8:conference.<yourdomain>
otherName.4 = 1.3.6.1.5.5.7.8.5;FORMAT:UTF8,UTF8:proxy.<yourdomain>
```

**Comment by lukas2511** [comment]
This looks like something which would be stripped by Let's Encrypt / Boulder anyway, or is this supported? Have you tried this using a custom csr?

**Comment by kermitDerFrosch** [comment]
Seems like it is supported. I make my xmpp certs with this  othername directive and sign them with the pathed version. I never have problems. If I make a cert without it, I get s2s errors from the server.

**Comment by lukas2511** [comment]
Okay, I merged your changes since they shouldn't interfere with anything else and if that makes dehydrated work for you (and probably a few other people) that's great :smile: Thanks for the suggestion.
