### ISSUE TITLE
config file order

### ISSUE THREAD

**Issue by rprimet** [lukas2511/dehydrated#358]
Hi,

Should "more-specific" (local) config files (e.g. in SCRIPTDIR or PWD) take precedence over "less specific" ones (e.g. /etc/dehydrated)? 

If so, a solution would be to change the search order in `load_config`.

**Comment by rprimet** [comment]
(reopening this issue -- using the -f flag may be the best choice, but it seems that giving precedence to local over global files still deserves thinking about?)

**Comment by txr13** [comment]
I would want the script to explicitly prefer global defaults (if they exist) over whatever local configs may have been accidentally created. If I want to use a non-global config (without removing an existing global config), I can specify that.

**Comment by rprimet** [comment]
OK, closing it for good then :)
