### ISSUE TITLE
Feature Request: Add alternative names to hook script calls

### ISSUE THREAD

**Issue by patrickdk77** [lukas2511/dehydrated#360]
Add a method to pass the subject alt names to the hook script, so the hook script and process these. Ideal for use with adding TLSA dns records after certificate signing.

**Comment by towolf** [comment]
I would also like to create symlinks for all alternative names. I assume the request from this issue is required for that?

**Comment by lukas2511** [comment]
Since 367ef574f154ad60acfeaa0101917f6da898cb24 `altnames` should be exposed as environment variable, you can take the names from there.

**Comment by towolf** [comment]
Thanks!
