### ISSUE TITLE
Make symlink names configurable

### ISSUE THREAD

**Issue by leeps** [lukas2511/dehydrated#368]
dehydrated creates symlinks to the current PEM-encoded certificate files. These are named

- `cert.pem` (and `cert.csr`) for the certificate (resp. the CSR)
- `chain.pem` for the intermediary certifcate, which the server needs to send too
- `fullchain.pem` for the concatenation of the above two
- `privkey.pem` for the file containing the private key

Please make the names of these links configurable. It would help with integration where not all certificates are managed by dehydrated.

**Comment by lukas2511** [comment]
For integration you can use a `deploy_cert` hook, this hook is exactly intended for that purpose. Just write a simple script that copies the certificates to where you want them.
