### ISSUE TITLE
Not working in FreeBSD systems

### ISSUE THREAD

**Issue by D4rk4** [lukas2511/dehydrated#376]
If i try run directly from TSH all working fine, if i try run under cron i get message "ERROR: This script requires curl."

**Comment by rumpelsepp** [comment]
Then please adjust your PATH line in your crontab. this script runs fine under FreeBSD.

```
$ which curl
```

Gives you a hint where the executable lives; then add this folder to the PATH for cron. that should be somewhere in the crontab.
