### ISSUE TITLE
Patch for configuring openssl command

### ISSUE THREAD

**Issue by s5410s** [lukas2511/dehydrated#379]
I installed openssl and libressl together, and I wrote patch for switching between them

New configuration keyword: OPENSSL_CMD="openssl"

[patch.zip](https://github.com/lukas2511/dehydrated/files/916415/patch.zip)

**Comment by O2Graphics** [comment]
Hello,

I'm not sure it's the best way to contribute on Github with a patch as a .zip file.
Anyway, to use LibreSSL, you don't need to add a new paramater, you can just add:
`alias openssl='/usr/local/bin/openssl'` in your dehydrated's config file.

Best Regards.
