### ISSUE TITLE
Adding email address to an account

### ISSUE THREAD

**Issue by sixtyfive** [lukas2511/dehydrated#380]
Hi! According to https://letsencrypt.org/docs/expiration-emails/ it's possible to update the email address stored with a LE account. They also mention `certbot register --update-registration --email yourname+1@example.com` as a command to use if you unsubscribed and want to resubscribe. In my case, I forgot to add a `CONTACT_EMAIL` to `config`, so there never was an email address attached to any of my accounts. Is something like the above `certbot` command possible with `dehydrated`, and if so, how?

**Comment by sixtyfive** [comment]
Ping?

**Comment by txr13** [comment]
This feature does not currently exist within `dehydrated` - see #239 and #328 for more discussion.

**Comment by sixtyfive** [comment]
Thank you for the links, @txr13!
