### ISSUE TITLE
Clear/Reuse pending authorizations 

### ISSUE THREAD

**Issue by KimBrodowski** [lukas2511/dehydrated#387]
I'm running a server behind a dynamic IP. Just before a cert was about to expire and the cronjob to renew it kicked in the IP address changed. Due to a 2nd instance of dehydrated running on the same network LE's dns servers had cached the old IP address for 60 seconds (DNS TTL).
This lead to a situation where requests could not be verified and many pending authorizations were created ultimately leading to hitting LE's rate limit. This can easily be avoided by either deactivating the authorizations explicitly if one in the chain required for the cert fails or just trying to validate them. It doesn't matter if the request succeeds or not: The pending authorization will be gone. Alternatively dehydrated could cache the values and use them in later requests. 

A similar issue and the solution mentioned above is documented on the LE forums here: https://community.letsencrypt.org/t/clear-pending-authorizations/22157

**Comment by lukas2511** [comment]
This is no longer relevant, authorizations should now be automatically re-used on serverside, any further (DNS or other) caching issues are outside the scope of dehydrated.
