### ISSUE TITLE
Sanity check on domains.txt

### ISSUE THREAD

**Issue by danb35** [lukas2511/dehydrated#390]
Testing an issue that's kind of related to #Issue 296 the other day, and I'd forgotten to enter any FQDNs into domains.txt.  Complete user error.  But the output when doing so was just:
`[root@dehydrated-test ~]# dehydrated -c`
`# INFO: Using main config file /etc/dehydrated/config`
`[root@dehydrated-test ~]# `

It might be helpful to have a message like "# ERROR: Nothing in /path/to/domains.txt, nothing to do!"  Would have saved me some time, anyway.

**Comment by lukas2511** [comment]
Mh... I see this more or less as intended behaviour. If you tell it to do nothing it just does nothing ¯\_(ツ)_/¯
