### ISSUE TITLE
value of ${issuer_cert_uri} part of chain.pem

### ISSUE THREAD

**Issue by hefty-pty** [lukas2511/dehydrated#392]
since commit 6a32f20e004b9d835cd02de9d78300be02784cf1 the value of ${issuer_cert_uri} precedes the certificate in chain.pem and is also part of fullchain.pem. deleting line 671 should remove that issue (i hope that's not a feature I don't understand)

```
--- a/dehydrated
+++ b/dehydrated
@@ -668,7 +668,7 @@ walk_chain() {
     local next_issuer_cert_uri
     next_issuer_cert_uri="$(get_issuer_cert_uri "${tmpcert}")"
     if [[ -n "${next_issuer_cert_uri}" ]]; then
-      printf "\n%s\n" "${issuer_cert_uri}"
+      printf "\n%s\n" "${issuer_cert_uri}"
       cat "${tmpcert}"
       walk_chain "${tmpcert}" "${next_issuer_cert_uri}"
     fi
```

**Comment by lukas2511** [comment]
Yea it's part of fullchain.pem, but what's the issue with that?

From what I understand from the RFC everything between encapsulated data blocks is considered an annotation and should not be interpreted.
I didn't find any issues with this ever, so why remove the potentially helpful comment from the file?

**Comment by hefty-pty** [comment]
sorry, I wasn't aware that comments should be tolerated in a .pem-file.
