### ISSUE TITLE
Can't make the -o option work

### ISSUE THREAD

**Issue by mrik974** [lukas2511/dehydrated#398]
Hi,
I'm using 0.4.0 version with different hooks (including one that only prints the token and lets me 60 seconds to modify the DNS myself)
I wanted to use dehydrated in a script and tried to use the `-o` option, but it fails to put the pem files in the specified directory.
My user has the correct right for the specified directory (it was created with the script to contain the csr file)
Then I use this command:
`./dehydrated -s 'certs/<domain_name>.csr' -d <domain_name> -t dns-01 -k 'hooks/ovh/hook.py' --out  'certs/<domain_name>'`
But the certificate is printed in `stdout` and the directory remains empty. Is there something i'm doing wrong ?

**Comment by txr13** [comment]
Well, the parameter description for `-s` should give you a hint...

`Sign a given CSR, output CRT on stdout (advanced usage)`

The `-o` parameter isn't used when you're just signing a CSR. It will only print to stdout.

**Comment by mrik974** [comment]
My bad, indeed I was missing something. Thank you
