### ISSUE TITLE
CI Environment

### ISSUE THREAD

**Issue by TBGG1** [lukas2511/dehydrated#399]
Hello,

When I try to config dehydrated, there comes the error "ERROR: Not running in CI environment!".
What does that mean and what do I have to do now?

Thanks in advance

**Comment by lukas2511** [comment]
Use `dehydrated` and not `test.sh`.

**Comment by TBGG1** [comment]
The command I used was "./dehydrated --config /home/www/letsencrypt.sh/conf/config.sh -c".
How do I do what you said?

**Comment by gheja** [comment]
It is strange you see that message as it appears only in test.sh and it is shown if the `CI` environment is set to `true`:

https://github.com/lukas2511/dehydrated/blob/ad21b41e272f2dd54e659ca39fb04e57a10225d7/test.sh#L7

What environment are you running it in? Maybe your env is trying to run the test.sh.

**Comment by TBGG1** [comment]
I have no clue what is ment by environment. I am going onto my server over SSH which runs Apache on Debian.

**Comment by gheja** [comment]
That's what I meant by environment :) It is still strange, it should not try to run test.sh.

Anyways, if you'd like you can try to run `export CI="true"` before running the dehydrated but be advised, I have not checked the test.sh script and I think there's a reason it checks for this variable (i.e. it might break the system it runs on which should not be a problem for a CI environment (as that is reset on each run)). So try this at your own risk.

**Comment by TBGG1** [comment]
Thank you very much. I might try that after contacting my webhoster.
