### ISSUE TITLE
Feature request: specify multiple hooks for multiple DNS providers at same time

### ISSUE THREAD

**Issue by aijanai** [lukas2511/dehydrated#402]
Hey,

I'd like to emit a certificate with ALT names for example.org and example.com
BUT example.org is managed by CloudFlare and example.com by Route53. So I can't use the same hook with the two providers because one of the two will fail.

Do you think this can be interesting to be implemented, or is it such a corner case that it's not worth the time?

Thanks

**Comment by txr13** [comment]
I'd suggest writing a hook that can handle this case. For example, write a hook-specific config file that matches domains to DNS providers. Then, your hook can match the passed domain to the config file and call the next script in turn.

Basically, you need to create a "master" hook script that can be called by `dehydrated` which will then handle the logic of figuring out what other hooks should be called in which cases.

**Comment by lukas2511** [comment]
I'd do what @txr13 suggested, this is really worth implementing in dehydrated itself.

If you split to multiple certificates you can always define other hook-scripts (see [per-certificate-config](https://github.com/lukas2511/dehydrated/blob/master/docs/per-certificate-config.md)), but for a single certificate using a "master" script that splits to the corresponding sub-hooks is your only option.
