### ISSUE TITLE
Hook for restart Nginx after renewing

### ISSUE THREAD

**Issue by petarkozic** [lukas2511/dehydrated#409]
Hi, because this script is used on mailcow mail instances, after each renewing, Nginx stop working and mail stop receiving due to restart Nginx.

Does this script have some hooks for restarting Nginx after renewing.

Thanks!

**Comment by lukas2511** [comment]
Please, if you gonna ask these questions read the documentation first. I'll answer anyway, but these already answered questions are annoying...

Basically you can use two hooks, one would be the `deploy_cert` hook which gets called after a new certificate has been issued (normally to copy it somewhere, but you don't need to do that, you can just reload your webserver), or you could use the `exit_hook` which gets called after every run (for a small webserver which probably is only used for some webmail and the challenge tokens a reload a week probably won't hurt anybody).

**Comment by petarkozic** [comment]
Thank you lukas on answer. I know, you close this issue, but I read documentation and I don't understand how to integrate that. I'm using mailcow instance with yours script and config file.
Please, if you can help me how to integrate this.

**Comment by petarkozic** [comment]
@lukas2511 
Please, can you give me answer ?

**Comment by txr13** [comment]
@petarkozic I would suggest using the example hook in the documentation, and customizing the desired function from there. Make sure the function is white-listed and the hook is set correctly in your config / calling script.

**Comment by lukas2511** [comment]
@petarkozic sorry I'll not be holding your hand going through this, I'd recommend reading the documentation and looking at howtos and examples that other people already published
