### ISSUE TITLE
Duplicate short parameter "-a"

### ISSUE THREAD

**Issue by derdanne** [lukas2511/dehydrated#410]
There is a duplication of the short parameter "-a" for "--account" and "--algo". After the update today all my certificate requests failed with "Unknown parameter detected: rsa". 

We should remove the short parameter "-a" for account, so all software that uses your script (ie. puppet modules) will continue to work.

**Comment by lukas2511** [comment]
Thanks for reporting this! I removed the short option for --account.

**Comment by derdanne** [comment]
Thanks!
