### ISSUE TITLE
startup_hook defined but not functioning

### ISSUE THREAD

**Issue by mabeltron** [lukas2511/dehydrated#411]
Putting this here as a note in case anyone downloads from Master before you get up...
There is an undefined subroutine 'startup_hook' being requested which causes the script to fail. It looks like this is a work in progress but I would suggest using 0.4.0 until this is completed.

**Comment by lukas2511** [comment]
This should just be a problem with your hook script, please see the newer example hook for someting that won't fail every time I add a new hook...
