### ISSUE TITLE
CA_REVOKE_CERT Unbound

### ISSUE THREAD

**Issue by taylorotwell** [lukas2511/dehydrated#413]
Starting today, all our customers have started receiving this error when issuing certificates using deydrated:

```
# INFO: Using main config file /root/letsencrypt1500328841/config
./dehydrated: line 415: CA_REVOKE_CERT: unbound variable
```

**Comment by csandescu** [comment]
You can easily fix that by using lazy evaluation in bash like this:

`if [[ "${statuscode}" = "409" ]] && [[ "${2}" = "${CA_REVOKE_CERT}" ]]; then`

However, after fixing it I'm getting:

>   + ERROR: An error occurred while sending post-request to https://acme-v01.api.letsencrypt.org/acme/new-cert (Status 500)
> 
> Details:
> {
>   "type": "urn:acme:error:serverInternal",
>   "detail": "Error creating new cert",
>   "status": 500
> }

So I guess there's something more to it.

C/

**Comment by lukas2511** [comment]
@taylorotwell can you please test with the newest version? this should be fixed now
