### ISSUE TITLE
OPENSSL variable not in config file

### ISSUE THREAD

**Issue by txr13** [lukas2511/dehydrated#414]
I noticed that the new `OPENSSL` variable added in commit https://github.com/lukas2511/dehydrated/commit/db18820991ba6f7e483aee941ee8f58e6e9b1457 doesn't add a corresponding item to the `config` file. Is this omission by design, or an oversight?

**Comment by lukas2511** [comment]
Thanks, this was an oversight, I just added it to the example config.
