### ISSUE TITLE
Responding to challanges when many SANs

### ISSUE THREAD

**Issue by belliash** [lukas2511/dehydrated#418]
I got a question / problem regarding responding to challenges.

Actually, according to dehydrated output, it requests a challange for all SANs in CSR and then launches a hook, which inserts TXT record. After wards it sends a response to challange and cleanup TXT records. Then repeat.

My problem is that I need to wait few minutes to propagate the changes in DNS. If I add a sleep to hook after inserting TXT record it takes a lot of time to wait for every TXT record.

What would solve my problem is to add all TXT records, wait some time, respond to all challanges and finally cleanup all TXT records.

Is that possible with dehydrated?

**Comment by txr13** [comment]
You should look into the HOOK_CHAIN parameter. It's designed for exactly this sort of issue.

**Comment by belliash** [comment]
That's it! Thanks.
