### ISSUE TITLE
Save certificate to file with --signcsr

### ISSUE THREAD

**Issue by belliash** [lukas2511/dehydrated#419]
Actually --signcsr outputs certificate to stdout and --out parameter is not used.
Please implement ability to specify a location with output ceritificate file.

**Comment by lukas2511** [comment]
Just use `dehydrated --signcsr /path/to/cert.csr > cert.pem`, no need for a parameter.

**Comment by belliash** [comment]
This is not a solution, because on any error this would overwrite valid certificate with empty file.

**Comment by txr13** [comment]
Why is it not a solution? Write it out to a temporary file, then check to make sure it's a valid cert (and not empty or an error message). If it is a valid cert, move it into the correct location and do whatever else is necessary.
