### ISSUE TITLE
dehydrated doesn't call le-godaddy-dns Python hook

### ISSUE THREAD

**Issue by roschler** [lukas2511/dehydrated#421]
I have dehydrated and the le-godaddy-dns Python configured on my system.  But I don't think dehydrated is calling the hook nor does it throw any error messages.  Here is my command line:

    ./dehydrated --config /home/user9/config  --hook /home/user9/le-godaddy-dns/godaddy.py --cron

When I run this in my bash script that sets the GoDaddy production key and secret, it immediately returns with the usual message about registering first.  I already have registered and I see my account in the account directory.  Also if I run the register command again it tells me that I am already registered.

As an additional test, I ran the godaddy.py script directly from the command line.  It immediately throws an error message telling me the GoDaddy key/secret can't be found.  This is of course because I am running it outside my script that exports those variables and then launches dehydrated with the le-godaddy-dns hook.

As a final test I ran the dehydrated command line shown above outside of the script that sets the GoDaddy key/secret.  **There were no error messages complaining about the key/secret not being found**.  There weren't any error messages at all, just the reminder to be registered and the info message saying that the output should tell me where my certs are.  There was no such output.  Also, I triple-checked the certs directory set in my config file and it is empty.  As I said, I don't believe the Python hook script is being run at all.

My belief is that the hook is not being run and dehydrated is failing silently.  What can I do to fix this?

**Comment by roschler** [comment]
It looks like the actual accounts directory and the directories where dehydrated looks for the accounts directory got out of sync somehow.  I figured this out after I sprinkled variable dump ECHO statements in the dehydrated script until I sussed out the problem.  It might be helpful to add the line "'accounts' directory not found.  If you already registered make sure your accounts directory is <put expected places here", so that people know the reason they are seeing the register reminder is because the script can't find that directory.

Unfortunately I'm now getting the following error during the le-godaddy-dns hook execution.  I'll post a full help request on the le-godaddy-dns forum:

{'message': 'The given domain is not registered, or does not have a zone file', 'name': '_Class', 'code': 'UNKNOWN_DOMAIN'}

**Comment by roschler** [comment]
I'm hitting all the speed bumps.  That error occurred because I was adding the "www" form of the domain name and it turns out that domain did not have a "www" DNS entry.  The error went away when I altered domains.txt and only submitted the non-www domain name (no sub-domain at all).

Unfortunately I'm getting a "wrong tag" failure but I reported that in a reply on another thread on this forum so I won't duplicate it here.

**Comment by lukas2511** [comment]
Are you running dehydrated from the debian repositories? Can you try the latest master version?

**Comment by roschler** [comment]
I cloned the dehydrated repository directly.

**Comment by lukas2511** [comment]
Those errors are coming from openssl, can you post the output of `dehydrated --version`? Ideally close this ticket (I don't give support for hook scripts, especially not those made by others) and create a new one with a better title and more details on what exactly you are doing. Without any information I'll not be able to debug that openssl error.

Also the "problem" you have with the accounts directory is actually a feature, by default it's always looking next to the config file, and if you temporarily create a file somewhere else and try to use it the script will also change location for the accounts directory. This is documented behavior and I will not add warnings for something like that.
