### ISSUE TITLE
version information on FreeBSD

### ISSUE THREAD

**Issue by welwood08** [lukas2511/dehydrated#426]
I noticed there's a couple of very minor things that don't work in the version information on my system (FreeBSD 10.3 jail on FreeNAS 9.10 host):
```bash
$ ./dehydrated --version
#
# !! WARNING !! No main config file found, using default config!
#
Dehydrated by Lukas Schauer
https://dehydrated.de

Dehydrated version: 0.4.0
GIT-Revision: 0be0ab083f290afbc757b8388a80df458ddfd33c

cat: /etc/issue: No such file or directory
OS:
Used software:
 bash: 4.4.12(2)-release
 sed: sed: illegal option -- -
 curl: curl 7.55.1
```
At this point the program is hanging waiting for Ctrl+D, after that it resumes:
```bash
 awk: awk: unknown option -W ignored
 grep: grep (GNU grep) 2.5.1-FreeBSD
 mktemp: mktemp: illegal option -- -
 diff: diff (GNU diffutils) 2.8.7
 openssl: OpenSSL 1.0.2l  25 May 2017
```
Not super important in my opinion, although I was momentarily confused by the hang while awk was waiting for input.

**Comment by lukas2511** [comment]
This should be fixed with ce9b42d8ad5bc225b7eeeaf47df0690b5d6b54e3 and bc20ec79f3a0edc30b53ed532cdf3e17169f12a6.
