### ISSUE TITLE
Example for GoDaddy API removes any TXT records you might already have

### ISSUE THREAD

**Issue by flamingm0e** [lukas2511/dehydrated#430]
Had this hit us a couple of times now.  Finally tracked it down to the GoDaddy API call in the example.
The example included will automatically remove any TXT records you have in your DNS manager.

https://github.com/lukas2511/dehydrated/wiki/Example-of-DNS-01-via-GoDaddy-API

`curl -X PUT https://api.godaddy.com/v1/domains/$domain/records/TXT -H "Authorization: sso-key $apikey:$secret" -H "Content-Type: application/json" -d "[{\"name\": \"_acme-challenge.${2}\", \"ttl\": 600, \"data\": \"${4}\"}]"`

The documentation lists another option.
https://developer.godaddy.com/doc#!/_v1_domains

`/v1/domains/{domain}/records/{type}/{name}`

I fixed this for my needs by changing the line to:
`curl -X PUT https://api.godaddy.com/v1/domains/$domain/records/TXT/_acme-challenge.${2} -H "Authorization: sso-key $apikey:$secret" -H "Content-Type: application/json" -d "[{\"name\": \"_acme-challenge.${2}\", \"ttl\": 600, \"data\": \"${4}\"}]"`

A disclaimer in the Wiki for this example would be a nice to have.  It removed my SPF records twice now.

**Comment by RyanSquared** [comment]
You can add a disclaimer yourself, it looks like the wiki is user-editable.

**Comment by lukas2511** [comment]
The wiki and the mentioned hook scripts and tutorials are user maintained.
Like @RyanSquared said you can add a disclaimer yourself.

This is not a dehydrated bug, closing this issue.

**Comment by JBHaire2004** [comment]
"A disclaimer in the Wiki for this example would be a nice to have. It removed my SPF records twice now."

Disclaimer: If you run commands you don't understand; the execution of those command may result in outcomes you don't like.
