### ISSUE TITLE
CSR generated through dehydrated script doesn't contains 'O', 'OU', 'C' parameters

### ISSUE THREAD

**Issue by kansal15** [lukas2511/dehydrated#439]
Hi,

I am using the latest dehydrated script for Let's Encrypt certificate issuance.
I successfully got the SSL cert from LE for my domain through using dehydrated script.

In my certificate, 'Organisation', 'Organisation Unit' and 'Country' attributes was blank. Then i check the same in my CSR and i got to figure out that my CSR doesn't contains the said attributes.

Any way to add those attributes in CSR while processing the certificate request.

Thanks.

**Comment by jobe1986** [comment]
It is worth noting LetsEncrypt strips out any fields from the subject identifier other then a commonName (CN) containing the primary host name of the certificate. So even if your CSR contained them, the certificate issued by LetsEncrypt would not.

This is especially given the case that the organization (o) field implies the certificate is an organization validated (OV) certificate which is not a service LetsEncrypt provide.

**Comment by lukas2511** [comment]
Exactly, as @jobe1986 said those fields are not copied over to the certificate, there is no point in setting them. Sorry for the late response.
