### ISSUE TITLE
Crontab

### ISSUE THREAD

**Issue by dulemis** [lukas2511/dehydrated#440]
Having an issue with crontab. On the command line everything works, but in crontab the ouput of the same command is  (sent to file):

# INFO: Using main config file /jffs/LetsEncrypt/config

Nothing more. When running it on the command line everything works, I'm amanually specifying the configuration path with --config. Any idea what could be causing this?

**Comment by jobe1986** [comment]
Are you running it directly from the crontab or are you wrapping it in a script?

**Comment by dulemis** [comment]
Directly, but I have tried your suggestion too without any change.

**Comment by Aikhjarto** [comment]
Just a wild guess: A common pitfall using crontab is the $PATH environmental variable. On lots of systems an application started from a shell (with a user logged in) uses a different $PATH variable than the same application started via crontab.
So make sure to have all tools required by dehydrated in the $PATH that is used by crontab.

**Comment by dulemis** [comment]
I've run a test script with cron outputting the path, and compared it with the path with the same user logged on to the shell. Do you see any differences that could be causing the problem?

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/opt/sbin:/opt/bin SHELL=/bin/sh

# echo $(env)
PATH=/opt/bin:/opt/sbin:/bin:/usr/bin:/sbin:/usr/sbin:/home/root:/mmc/sbin:/mmc/bin:/mmc/usr/sbin:/mmc/usr/bin:/opt/sbin:/opt/bin:/opt/usr/sbin:/opt/usr/bin: SHELL=/bin/sh

**Comment by Aikhjarto** [comment]
Obviously the $PATH is different.
Just make them equal and see if anything changes.

**Comment by dulemis** [comment]
Thank you very much, I added it to the wrapper shell script and it did the trick!
