### ISSUE TITLE
Issue with failing to acquire root domain certs

### ISSUE THREAD

**Issue by Timetreck** [lukas2511/dehydrated#445]
Errors on just the root domain, on www. it validates and issues a cert fine. 

Also worth noting -- last week this worked fine on a bunch of other domains. But twice today this has come up, on two entirely different domains.

I've considered this could be a CAA record problem, but I'm fairly sure it's not after digging into both domains.

 INFO: Using main config file /etc/dehydrated/config Processing domain.com with alternative names: www.domain.com  + Signing domains...
 + Creating new directory /etc/dehydrated/certs/domain.com ...
 + Generating private key...
 + Generating signing request...
 + Requesting challenge for domain.com...
 + Requesting challenge for www.domain.com...
 + Responding to challenge for domain.com...
 + Responding to challenge for www.domain.com...
 + Challenge is valid!
 + Requesting certificate...
  + ERROR: An error occurred while sending post-request to https://acme-v01.api.letsencrypt.org/acme/new-cert (Status 403)

Details:
{
  "type": "urn:acme:error:unauthorized",
  "detail": "Error creating new cert :: authorizations for these names not found or expired: domain.com",
  "status": 403
}

**Comment by txr13** [comment]
See #431.

**Comment by Timetreck** [comment]
Updated dehydrated to the latest and this is the error I get now:

It may be a webserver config problem, but I just wanted to make sure it's not something else. 

INFO: Using main config file /etc/dehydrated/config Processing domain.com with alternative names: www.domain.com  + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting challenge for domain.com...
 + Requesting challenge for www.domain.com...
 + Already validated!
 + Responding to challenge for domain.com...
ERROR: Challenge is invalid! (returned: invalid) (result: {
  "type": "http-01",
  "status": "invalid",
  "error": {
    "type": "urn:acme:error:connection",
    "detail": "Fetching http://domain.com/.well-known/acme-challenge/dnxByHUZsidE4fyG7N0HeWu7tyjyIf1MY8lVsBkgzlI: Timeout",
    "status": 400
  },
  "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/FxQzsh54BvUA9YTS1TjV3ItOSf4jo54txw4-Xvuqkis/2231839467",
  "token": "dnxByHUZsidE4fyG7N0HeWu7tyjyIf1MY8lVsBkgzlI",
  "keyAuthorization": "dnxByHUZsidE4fyG7N0HeWu7tyjyIf1MY8lVsBkgzlI.3uMsTTCiuRJRG1ajofVu8FCAbuYKHHUPYbGkoeN4ElU",
  "validationRecord": [
    {
      "url": "http://domain.com/.well-known/acme-challenge/dnxByHUZsidE4fyG7N0HeWu7tyjyIf1MY8lVsBkgzlI",
      "hostname": "domain.com",
      "port": "80",
      "addressesResolved": [
        "1.2.3.4",
        "5.6.7.8"
      ],
      "addressUsed": "1.2.3.4",
      "addressesTried": []
    }
  ]
})

**Comment by txr13** [comment]
The error says that LE timed out while trying to access the validation path. (http://domain.com/.well-known/acme-challenge/dnxByHUZsidE4fyG7N0HeWu7tyjyIf1MY8lVsBkgzlI)

I would suggest placing a dummy file in the acme-challenge directory and seeing what happens when you try to access it with that domain name, see if that sheds any more light on the issue.

**Comment by Timetreck** [comment]
Figured it out, was a strange webserver issue. Thanks!
