### ISSUE TITLE
Does Dehydrated "remember" used hooks?

### ISSUE THREAD

**Issue by BnMcG** [lukas2511/dehydrated#448]
Quick question... Say I have two separate domains, and they are verified using two separate hooks (I'm mainly thinking one uses a HTTP challenge while one uses DNS).

If these certificates are generated, will dehydrated "remember" the hooks and challenge methods used when launched with the -c cron parameter, or will I need to create a new cron job for each type of challenge / hook?

**Comment by jobe1986** [comment]
When I setup one of my certs I used HTTP challenge for one cert amongst several that I use DNS challenge for. To do so I followed the information in docs/per-certificate-config.md

**Comment by lukas2511** [comment]
It doesn't remember, but as @jobe1986 said you can configure it for each certificate so you don't have to use multiple cronjobs.
