### ISSUE TITLE
Specify separate certificate files

### ISSUE THREAD

**Issue by BnMcG** [lukas2511/dehydrated#452]
I'm using per-domain config for my certificates, and that is working fine. However, all my domains are specified in one domains.txt, and consequently all domains are generated as one certificate. 

Is there a way to specify that a new, separate, certificate should be generated for each domain name?

Thanks.

**Comment by jobe1986** [comment]
Each line of domains.txt is a separate certificate, with the first host name on each line being treated as the primary host name for that certificate.

For example if you have a domains .txt such as the following, you will get 2 certificates, one for a.example.com and b.example.com and another for c.example.com:
```
a.example.com b.example.com
c.example.com
```

**Comment by alainwolf** [comment]
Certtificates are are separated by new lines in domains.txt.
All domains in the same line are included in one certificate, but for every line a different certficate should be generated. Thats how /docs/domains_txt.md describes it, and how it works on my system.

**Comment by BnMcG** [comment]
Ahah, thanks! That's what I was missing - sorry! My script is just outputting everything onto one line. Thanks for highlighting that in the docs for me, I just assumed it'd be something more complex.
