### ISSUE TITLE
Too talkative

### ISSUE THREAD

**Issue by bortzmeyer** [lukas2511/dehydrated#455]
By default, `dehydrated --cron` is very talkative:

```
Processing dns.bortzmeyer.org
 + Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till Jan 23 05:25:11 2018 GMT Certificate will not expire (Longer than 30 days). Skipping renew!
```

This triggers an email from cron, whcih is useless.

I find no option to make dehydrated more quiet. Redirecting to /dev/null is of course not an option, since I still want to know when the certificate is renewed.

**Comment by bortzmeyer** [comment]
It was apparently already requested in #47 and #331 but never solved.

**Comment by lukas2511** [comment]
This will stay this way unless somebody puts work into a logging system.
I personally really really like verbose output and if you want to run it in a cronjob you should have a look at the suggestions from those past tickets (use a special "wrapper" tool and hooks).
