### ISSUE TITLE
.gitignore add challenges/*

### ISSUE THREAD

**Issue by gertcuykens** [lukas2511/dehydrated#459]
Can `challenges/*` be added to .gitignore please thx

**Comment by lukas2511** [comment]
I was asked this several times by now, and I'm still saying no.

My opinion on this is that public(!) challenge files have nothing to do right next the very private key files, they should be somewhere like /var/www and considered completely public.

**Comment by gertcuykens** [comment]
I put boilerplate code in it that dispatches the challenges either true `scp` or `gcloud app deploy acme.yaml --project $(PROJECT)`  it's like a extension of the hook.sh script. In case of `scp` i can find a work around referring to /tmp or something but in case of gcloud it gets messy to put it somewhere else

**Comment by lukas2511** [comment]
You can add a local exclusion using `.git/info/exclude`, but I'm suggesting to find a way to work with a tmp directory.
