### ISSUE TITLE
Which file for ssl_trusted_certificate in nginx conf with OCSP?

### ISSUE THREAD

**Issue by pandark** [lukas2511/dehydrated#470]
I'm a bit confused about OCSP… I saw some talk about a `.der` file but there is no such file in `${CERTDIR}/<DOMAIN_NAME>/` where my `.csr` and `.pem` are, even though I set `OCSP_FETCH` and `OCSP_MUST_STAPLE` to "yes".

Should this file exist, or am I supposed to use `fullchain.pem` as I saw in some example config elsewhere?

**Comment by lukas2511** [comment]
`ssl_trusted_certificate` has nothing to do with ocsp, that value in nginx is for client tls authentication.

With `OCSP_FETCH=yes` in your config you should get a `certs/your.cert/ocsp.der` file, which you can use by setting `ssl_stapling_file "/etc/dehydrated/certs/your.cert/ocsp.der";` in your nginx configuration. If the `ocsp.der` link is missing double-check your config, it should be created when the dehydrated cron operation is running.

**Comment by lukas2511** [comment]
@pandark ocsp stuff was introduced in 0.5.0 which should be in stretch-backports by now

**Comment by pandark** [comment]
Unfortunately, only  0.4.0 is in stretch-backport.
Until it's there, I'm using the dirty-hack way, fetching all hosts from `domains.txt` with curl when nginx start or reload and it seems to work.

```
for domain in $(/bin/cat /etc/dehydrated/domains.txt); do
    echo "fetching https://${domain}/";
    /usr/bin/curl --silent --cert-status "https://${domain}/" >/dev/null;
done;
```

**Comment by lukas2511** [comment]
@pandark your mirror must be a bit behind, dehydrated 0.5.0 was approved in stretch-backports a few hours ago: https://packages.debian.org/stretch-backports/dehydrated

**Comment by pandark** [comment]
Yep. Cool! After a few adjustments everything is working 👍
