### ISSUE TITLE
New hook: Generate/Fetch external CSR

### ISSUE THREAD

**Issue by lukas2511** [lukas2511/dehydrated#475]
A new hook will be implemented which allows for external CSR generation or fetching, this should make it possible to use dehydrated to e.g. sign certificates for routers or similar more closed systems without handling their private keys.

**Comment by lukas2511** [comment]
The hook will probably be called `generate_csr`, and will have the names as listed in domains.txt as parameters.
All names for the certificate order will be extracted from the generated / fetched CSR, so domains.txt can basically contain a simple alias in this case.

**Comment by lukas2511** [comment]
Implemented in 63854b752ba7745dff3dc459f700bd594d25686e.

**Comment by Gnarfoz** [comment]
The host names of these devices will still need to be publicly reachable, though, right?
Or am I missing something here. 🤔

**Comment by lukas2511** [comment]
@Gnarfoz at least DNS has to be resolvable from outside so you can use DNS-01, you need to verify ownership of the hostnames in some way

**Comment by Gnarfoz** [comment]
That's what I figured. I'll have to look into DNS-based verification some more. Thanks for the quick reply (and dehydrated in general ❤️)!
