### ISSUE TITLE
KeyError: 'generate_csr' when building from master.

### ISSUE THREAD

**Issue by Asara** [lukas2511/dehydrated#476]
I've always just built from master (and am now using tagged releases).

This is along with the recommended cloudflare hook (kappataumu/letsencrypt-cloudflare-hook)

**Comment by lukas2511** [comment]
Hook scripts should just ignore any hooks they don't know. This is a bug in the mentioned hook script and not in dehydrated.

**Comment by lukas2511** [comment]
I added a random hook call in 9ebab3e026569e79971fd7be14c522b22025150d to make it extremely clear that unknown hooks should just be ignored.

**Comment by Asara** [comment]
Thanks @lukas2511

**Comment by kappataumu** [comment]
@lukas2511 Apologies for this, should have addressed the issue earlier.
