### ISSUE TITLE
KeyError cloudflare

### ISSUE THREAD

**Issue by kdulep** [lukas2511/dehydrated#477]
`./dehydrated -c -d example.etc -t dns-01 -k 'hooks/cloudflare/hook.py'`

```
# INFO: Using main config file /root/dehydrated/config
 + CloudFlare hook executing: *some key*
Traceback (most recent call last):
  File "hooks/cloudflare/hook.py", line 206, in <module>
    main(sys.argv[1:])
  File "hooks/cloudflare/hook.py", line 202, in main
    ops[argv[0]](argv[1:])
KeyError: '*some key*=='

```

**Comment by kdulep** [comment]
sorry wrong script, issue for hook script

**Comment by joeydc** [comment]
I was having this exact same error with le-godaddy-dns hook.
I've managed to make it work by using an old version of Dehydrated.
Here's my original post with the dev: josteink/le-godaddy-dns#15

**Comment by lukas2511** [comment]
@joeydc again: not a dehydrated issue, the hook script is broken. i replied to your ticket over on le-godaddy-dns to let the author know and dehydrated now tries to make it clear what's going on.

**Comment by joeydc** [comment]
@lukas2511 Awesome, thank you Sir !
