### ISSUE TITLE
Commits today appears to cause Dehydrated to exit with non-zero exit code?

### ISSUE THREAD

**Issue by taylorotwell** [lukas2511/dehydrated#479]
One of the changes made today appears to have started making Dehydrated start exiting with a non-zero status even when everything goes fine. We are seeing the problem on Laravel Forge.

**Comment by lukas2511** [comment]
Mh... Can you run something like `bash -x dehydrated -c` and post the last few lines before it exits?

**Comment by lukas2511** [comment]
I think this is related to the recent addition of the "hook-bricker". I did one more change in dcdb2940fbc4b8468cbbe75ea7725cf0a3306262, if that doesn't fix your problem your hook script probably is broken. It should ignore unknown hooks and exit cleanly, otherwise dehydrated won't work.

**Comment by lukas2511** [comment]
Sorry i think I found the issue. Should be fixed in a6e6aa74457c146e3a7de95c135b98e690dc0d41.
