### ISSUE TITLE
Dehydrated silently quits on -c, issue with hook

### ISSUE THREAD

**Issue by Janfred** [lukas2511/dehydrated#480]
`dehydrated -c` silently quits without doing anything in the current master

When commenting out this line (and adding an `echo ""` in the line after) it works as expected
https://github.com/lukas2511/dehydrated/blob/0ade30cc7482353982e34529a52d714bae691a24/dehydrated#L86

Tested on Debian Jessie and Ubuntu 14.04

**Comment by lukas2511** [comment]
I did one more change in dcdb2940fbc4b8468cbbe75ea7725cf0a3306262, if that doesn't fix your problem your hook script probably is broken. It should ignore unknown hooks and exit cleanly, otherwise dehydrated won't work.

**Comment by Janfred** [comment]
I don't have a hook script, so it can't be an issue with the script.

I'll check it again in a few hours if the issue is fixed

**Comment by lukas2511** [comment]
I think I know what is going on... should be fixed in a6e6aa74457c146e3a7de95c135b98e690dc0d41.
