### ISSUE TITLE
certificate for dehydrated.de expired

### ISSUE THREAD

**Issue by ploxiln** [lukas2511/dehydrated#492]
Firefox says:
> dehydrated.de uses an invalid security certificate. The certificate expired on March 9, 2018, 08:40. The current time is March 9, 2018, 11:53. Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by lukas2511** [comment]
It's fixed now, thank you. Domain was missed in my cronjob 🙈

**Comment by ploxiln** [comment]
thanks!
