### ISSUE TITLE
Request Cert on other port

### ISSUE THREAD

**Issue by CloudHoang90** [lukas2511/dehydrated#495]
Hi lukas
Thanks for your script.
by default, your script will request the certificate on the port 8123 but may I request a parameter to choose other port to request the certificate?

thanks

**Comment by txr13** [comment]
What do you mean by requesting it on a different port?

Dehydrated does not control the ports used at all. ACME servers run on a predetermined port. The challenges are laid out by the ACME specification. These are not optional.

Once you have a certificate, you can use it on any port you like. Dehydrated does not control this, either.

**Comment by lukas2511** [comment]
Yea, dehydrated doesn't control any ports, I didn't even know that something is using port 8123 ¯\\_(ツ)_/¯
