### ISSUE TITLE
Certificate file also contains chain for ACME v2

### ISSUE THREAD

**Issue by mvistein** [lukas2511/dehydrated#501]
The certificate retrieved from Let's Encrypt ACMEv2 endpoint (both staging and production) contains both the end certificate and the intermediate certificate (which is conforming to 7.4.2 of the ACME draft). As a result, now the fullchain.pem file contains the intermediate certificate twice.

**Comment by thias** [comment]
Also worth noting is that the intermediate certificate included in the `cert-<id>.pem` file seems to have Windows EOL, while the certificate above has proper UNIX EOL, so there a newline type mix in the file (this is on RHEL7).

**Comment by cpu** [comment]
> Also worth noting is that the intermediate certificate included in the cert-<id>.pem file seems to have Windows EOL

@thias I think this is a mistake on the Let's Encrypt side. I opened https://github.com/letsencrypt/boulder/issues/3557 to track fixing this.

**Comment by lukas2511** [comment]
Whoopsie. The easiest solution for this would be to just completely ignore the old `chain.pem` and just write the certificate directly to `fullchain.pem`, but that may break some setups...
I'll need to figure out how to extract just issuer certificates from a file with multiple certificates... I guess since they are in order I could just sed and grep my way to those certificates, but does anybody know a cleaner way?

**Comment by mvistein** [comment]
I think you could just process the file using the openssl x509 module.

On my system (version 1.0.2g) the following command yields the right result:

`openssl x509 -in cert.pem -out cert2.pem`

**Comment by lukas2511** [comment]
Should be fixed with 2533931cf1311e33252bc2492975afae71bd447f, thanks for reporting this issue.

**Comment by cpu** [comment]
> Also worth noting is that the intermediate certificate included in the cert-<id>.pem file seems to have Windows EOL, while the certificate above has proper UNIX EOL, so there a newline type mix in the file (this is on RHEL7).

@thias This is fixed and should be consistently UNIX newlines now. Thanks for flagging it.

**Comment by thias** [comment]
@lukas2511 @cpu : Thanks for the quick fixes. Let's Encrypt with wildcard certificates rocks! Thank you sooo much for your great work on your respective projects, it's MUCH appreciated.
