### ISSUE TITLE
domain specific config file

### ISSUE THREAD

**Issue by ksingvo** [lukas2511/dehydrated#505]
At the moment **all** config files in CONFIG_D/* are included when running dehydrated.

I'm asking to include a domain specific configuration file, which relies on the domains read from DOMAINS_TXT, to get ability of domain specific configuration settings, like CONTACT_EMAIL or any other.

Example:
domains.txt consists of:
* example.com
* example.net

When processing domain example.com a config file named "directory"/"example.com".sh should be parsed, but **not** "directory"/"example.net".sh
Similar when processing domain example.net: config file named "directory"/"example.net".sh should be parsed, but **not** "directory"/"example.com".sh

I'm open regarding the implementation details, and "directory" is only to be seen as a placeholder. :)

**Comment by txr13** [comment]
Please see the per-certificate config file - https://github.com/lukas2511/dehydrated/blob/master/docs/per-certificate-config.md.

**Comment by ksingvo** [comment]
Thanks. Wasn't aware.
But CONTACT_EMAIL isn't a supported option, is it?

**Comment by txr13** [comment]
CONTACT_EMAIL is set on the account level, not on the certificate level. To have a different CONTACT_EMAIL, you would need to create a completely separate account on the ACME server.

**Comment by ksingvo** [comment]
I see. Thanks for explanation.

**Comment by ksingvo** [comment]
As it is already implemented or not possible (reason given), this issue can be closed from my point of view.
