### ISSUE TITLE
dehydrated with zsh, sign_csr:86: challenge_identifiers: assignment to invalid subscript range

### ISSUE THREAD

**Issue by hshh** [lukas2511/dehydrated#511]
dehydrated 0.6.1, FreeBSD
Error after Handling authorization.
sign_csr:86: challenge_identifiers: assignment to invalid subscript range

**Comment by lukas2511** [comment]
Thanks for reporting, I fixed the issue and tested with zsh on Debian, I guess it should work on FreeBSD too.
