### ISSUE TITLE
Localhost setup

### ISSUE THREAD

**Issue by digikarl18** [lukas2511/dehydrated#519]
I was following a tutorial to setup a testing server on my imac running High
10.13.  At step 23 (of 25 steps) when I entered the following command:
sudo openssl req -extensions san -config /etc/ssl/openssl.cnf -x509 -nodes -newkey rsa:4096 -keyout /private/etc/apache2/server.key -out /private/etc/apache2/server.crt -days 365 -subj "/C=US/ST=Florida/L=Boca Raton/O=WebsiteBeaver/CN=localhost"
I got the following message:
Error Loading extension section san
Can you help me please?  I'm a 76-year-old retiree trying to dabble in website development as a hobby. I've had some Unix experience in the past.  I manage OK with websites that deals with the client side only, but I need to get into some server side processing.

**Comment by txr13** [comment]
What tutorial were you following? The command you’ve listed doesn’t have anything to do with dehydrated itself, so I’m a bit confused on how you got here.

**Comment by digikarl18** [comment]
I created a new GitHub account and attempted to create a “New Issue”.  I have no idea how it ended us a part of your thread.  Perhaps in my frustration in seeking an answer to my problem I did not pay enough attention to what I was doing.  I sincerely apologies for the error.  I will revisit the process and try to identify what I did wrong.

**Comment by digikarl18** [comment]
This is a test.Please Ignore!!

**Comment by danimo** [comment]
@lukas2511 I think this can be closed.
