### ISSUE TITLE
set: pipefail: invalid option name

### ISSUE THREAD

**Issue by etanol85** [lukas2511/dehydrated#520]
Trying to run dehydrated on an older (mac os x) system I'm running into this error:
dehydrated: line 10: set: pipefail: invalid option name

Output of bash -x dehydrated -c
```
+ set -e
+ set -u
+ set -o pipefail
 dehydrated: line 10: set: pipefail: invalid option name
```
Bash version is
`GNU bash, version 2.05b.0(1)-release (powerpc-apple-darwin8.0)`

On another Mac OS machine with a more recent bash version 
`GNU bash, version 3.2.48(1)-release (x86_64-apple-darwin10.0)` 
I do not get this error.

Is there any workaround for this?

**Comment by LwsBtlr** [comment]
On Mar 23, 2018, at 05:02, etanol85 <notifications@github.com> wrote:
> Is there any workaround for this?

brew install bash

-- 
This is my signature. There are many like it, but this one is mine.

**Comment by etanol85** [comment]
Many thanks, this (bash 4.4.) solved the issue!

**Comment by lukas2511** [comment]
Out of interest I just googled when pipefail was introduced. It seems it was introduced with bash version 3 which was released July 2004. Wow. But okay, you are running a powerpc setup, so I guess it's quite an old OS X version.

Installing bash from brew or ports definitively is the best solution for this, but I'm kinda wondering if the pre-installed zsh would work with dehydrated... mhm...

**Comment by etanol85** [comment]
Thanks, yes this is Mac OS 10.4 i think that Mac OS X 10.5.8 still can run on PPC  and comes standard with BASH 3.2.17 so in that case that could work out of the box.

FIY I tried the preinstalled zsh with "zsh ./dehydrated -v" and that did not work either:
./dehydrated:set:10: no such option: pipefail
./dehydrated:764: parse error near `local'

Thanks again!
