### ISSUE TITLE
ERROR: Validating this certificate is not possible using http-01. Possible validation methods are: dns-01

### ISSUE THREAD

**Issue by nadermx** [lukas2511/dehydrated#523]
I'm trying to use the domains.txt file with 

```*.domain.com > wildcard.domain.com```

But when I use it I get 

`ERROR: Validating this certificate is not possible using http-01. Possible validation methods are: dns-01
`
I'm having a pretty hard time finding how to do this

**Comment by lukas2511** [comment]
Please take a look at the documentation before opening issues like this: https://github.com/lukas2511/dehydrated/blob/master/docs/dns-verification.md

**Comment by jribbens** [comment]
It might be worth mentioning in the documentation that LetsEncrypt *require* `dns-01` validation for wildcard certificates. You might think it's obvious from the error message, but I did not find it so (the error doesn't mention that it's the wildcard-ness of the certificate that is the issue).

**Comment by 7eggert** [comment]
I second this. A closed issue does not replace proper documentation.

**Comment by txr13** [comment]
Let's Encrypt _has_ documentation on this: https://letsencrypt.org/docs/challenge-types/

You cannot use any client tool to perform an action prohibited by the CA. Therefore it's appropriate to review the documentation available from the CA before attempting to use any client to interact with it. If instead you want an overview of the ACME spec, the RFC is available online.

But if the question was actually "I'm having a pretty hard time finding how to do this [dns-01 validation]", then it's been answered in the most appropriate fashion--by linking to the existing dehydrated-specific documentation on performing dns-01 validation.

**Comment by 7eggert** [comment]
Sorry to have bothered you as there will be sent an email to myseld with a good explanation. I just was too fast and google was even faster directing me here.

I don't even expect domain validation to be possible using selfhost.de, but this may be untrue. That may or may be not my task for another day
