### ISSUE TITLE
ACMEv2(?): Intermediary (chain) placed in fullchain.pem twice.

### ISSUE THREAD

**Issue by Eihrister** [lukas2511/dehydrated#526]
Hi!

For some reason, when issuing my wildcard certificate (ACMEv2), it appears fullchain.pem ends up with the same intermediary certificate (chain.pem) twice.

I notice ^M line -endings in the first iteration of the intermediary in fullchain.pem, which do not exist in the chain.pem. However, upon opening cert.pem, it seems the intermediary is already there, with the ^M line-endings.

I suspect that with ACMEv2, the contents of chain.pem already comes from Let's Encrypt (hence being stored in cert.pem). 

Daniël

**Comment by txr13** [comment]
Please check your dehydrated version. This should be fixed in master a while back.

**Comment by Eihrister** [comment]
Yeah, Lukas just showed me on IRC as well. I was using 0.6.1, cloned the repo to make a fix, then tested with the same 0.6.1 release on a different machine that had my hook scripts. I need more caffeine.
