### ISSUE TITLE
generate Merged (key + fullchain) output

### ISSUE THREAD

**Issue by sHorst** [lukas2511/dehydrated#528]
I have some software, which prefferes to get a combined key and fullchain pem so only one file is loaded. It would be great, if the script would generate this in the certs directory next to the other output files, like fullchain (which is a combination of chain and cert as well) etc.

Right now i can do it with a hook, but it would be great, if you just run the script, and the combined/merged/privkey_fullchain/full.pem whould be generated

**Comment by lukas2511** [comment]
I don't want to add this feature, most software can handle separate files and I think that should be encouraged. If you need something like this you can easily create a hookscript to cat those files together. Thanks for the suggestion anyway!
