### ISSUE TITLE
Clean challenge via hook bug?

### ISSUE THREAD

**Issue by yarozen** [lukas2511/dehydrated#536]
i'm using the default HOOK_CHAIN="no" as i'm calling the deploy_challenge and clean_challenge function seperatel and in my case i'm using CHALLENGETYPE="http-01".
i notice that the function "clean_challenge" is not being called in such scenario.

i think that after these 2 lines:
```
      # Clean challenge token using non-chained hook
      [[ "${CHALLENGETYPE}" = "dns-01" ]] && [[ -n "${HOOK}" ]] && [[ "${HOOK_CHAIN}" != "yes" ]] && "${HOOK}" "clean_challenge" ${deploy_args[${idx}]}
```
some like this line should appear
`      [[ "${CHALLENGETYPE}" = "http-01" ]] && [[ -n "${HOOK}" ]] && [[ "${HOOK_CHAIN}" != "yes" ]] && "${HOOK}" "clean_challenge" ${deploy_args[${idx}]}`

is there a problem or am I missing something?

**Comment by lukas2511** [comment]
I recently restructured the loop because it left challenges in place after an invalid validation and I mistakenly added a check for dns-01 validations for the hook-call. Removed that check and everything should be fine now.
