### ISSUE TITLE
How to configure apache with existing vhost redirect/proxypass/AuthType rule?

### ISSUE THREAD

**Issue by dragetd** [lukas2511/dehydrated#537]
Using the config as explained here: https://github.com/lukas2511/dehydrated/blob/master/docs/wellknown.md#apache-example-config

I am trying to set up the .well-known/acme-challenge to be available under every vhost. But one vhost has for example 'Redirect permanent / https://foo.bar/cms.

This config forces a redirect and breaks the config.

Then there is
<Location> AuthType Basic… </Location> which also breaks the setting. :(

The apache config explains how the later rules take predesence https://httpd.apache.org/docs/2.4/sections.html#merge-examples

Does anyone know how to get around this? I could write excluding-rules and adjust every vhost config. But this is anything but pretty. :(

**Comment by lukas2511** [comment]
Sorry but this is not a dehydrated bug-report so I'm closing this. Your best bet would be to look around on the Let's Encrypt community forums, other clients require very similar configuration so you might find some help over there.

**Comment by dragetd** [comment]
True, but if there was some apache config option that would prevent it from being overwritten, it would be a great addition to the docs. :-) But I'll see what I can find out.
