### ISSUE TITLE
DNS-01 hook for Yandex.PDD DNS hosting in PHP

### ISSUE THREAD

**Issue by pasha1st** [lukas2511/dehydrated#550]
Hello! I've made DNS-01 hook for dehydrated for Yandex.PDD DNS hosting in PHP. <https://github.com/pasha1st/dehydrated-yapdd-hook>
Could you mention it in Wiki?

**Comment by jobe1986** [comment]
The wiki page in question ( https://github.com/lukas2511/dehydrated/wiki/Examples-for-DNS-01-hooks ) is editable by everyone at least with a github account as far as I can see. So you can easily add it yourself.

**Comment by pasha1st** [comment]
Ok, thanks, I added link myself
