### ISSUE TITLE
Incorrect .pem files with recent versions

### ISSUE THREAD

**Issue by lukavia** [lukas2511/dehydrated#558]
I've discovered that after installing the latest version my .pem files started to contain diffrent data: 
cert-xxxx...pem - contains the certificate and the chain
chain-xxxx...pem - contains the chain and a link above http://cert.int-x3.letsencrypt.org/ 
fullchain-xxxx...pem - contains the combination of the above. That is: the cert, the chain, the link, and the chain again.

**Comment by txr13** [comment]
Please run “dehydrated -v” and post the resulting output.

**Comment by txr13** [comment]
@lukavia You’re not using the latest version. Please upgrade—a fix for this has already been implemented.

**Comment by lukavia** [comment]
Since I install from debian packages I've posted a bug with them to upgrade the version https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=898254

**Comment by lukavia** [comment]
I confirm that this is fixed in 0.6.1-2
