### ISSUE TITLE
Does dehydrated fully support IDN's 'Internationalized Domain Names)?

### ISSUE THREAD

**Issue by EdNett** [lukas2511/dehydrated#564]
Does dehydrated fully support IDN's 'Internationalized Domain Names)?

Let's Encrypt does as of Oct 20, 2016, but we still don't have this functionality with Aegir (Drupal) BOA. Is this working, please?

Best,

Ed

**Comment by lukas2511** [comment]
Since IDNs are stored as punycode this shouldn't be a problem, just enter the corresponding punycode domains in your config and you should be good to go.
