### ISSUE TITLE
Script stops when run by cron

### ISSUE THREAD

**Issue by oddtwelve** [lukas2511/dehydrated#567]
The script works fine when I manually execute it, however, if I put it in crontab, here's what I get in the output:

Processing example.com
 + Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till Aug 12 16:29:12 2018 GMT Certificate will not expire
(Longer than 30 days). Ignoring because renew was forced!
 + Signing domains...
 + Generating private key...
 + Generating signing request...

... and nothing else.

No logs in syslog.

I'm sure it's something in my environment, but please, help to diagnose.

It runs fine in crontab on some other servers.

**Comment by lukas2511** [comment]
I'm assuming you already updated to the newest version from git and tried with that?
Could you provide the output of `dehydrated -v` and when running dehydrated using `bash -x /path/to/dehydrated [...]` (ideally run somehow from inside a cronjob)

**Comment by oddtwelve** [comment]
Ok, I got it working. I had not any MTA installed, so I could not see anything in syslog. The problem with path to openssl and openssl.cnf
