### ISSUE TITLE
Hook bash for DNS-01 challenge for pratically every domain (with Cloudflare) > GOT!

### ISSUE THREAD

**Issue by sineverba** [lukas2511/dehydrated#568]
I have a domain on an important Italian registrar, without possibility to add via API the TXT record for DNS challenge.

After a bit of study, I got my goal:

DNS challenge for "every" domain (using Cloudflare). CF has API... Only necessity is a registrar that permits DNS management.

This is my hook bash, feel free to use, edit, test, etc. It is under MIT license.

It works for me, I hope work for you and I would make it better.

https://github.com/sineverba/cfhookbash

At the end, thank you for dehydrated. It is a fantastic tool, really.

**Comment by lukas2511** [comment]
Feel free to add your hook to the wiki, the list on there is user-maintained. Thanks for the thanks ;)
