### ISSUE TITLE
No module named builtins

### ISSUE THREAD

**Issue by rschuetzler** [lukas2511/dehydrated#570]
How can I get dehydrated to use the python3.6 I installed on my Raspberry Pi? I've got Python there, and installed the `requirements.txt` with it. Unfortunately when I run dehydrated, it seems to be trying to run in the system-installed Python 2 instead. 

## Error message

```
# INFO: Using main config file /home/pi/dehydrated/config
Traceback (most recent call last):
  File "hooks/cloudflare/hook.py", line 8, in <module>
    from builtins import str
ImportError: No module named builtins
```

## What I've tried
* Creating a bash alias `alias python='python3.6'`
* Adding the alias to `config`
* Just installing the Python 2 requirements, but I get issues with `arm-linux-gnuabihf-gcc` when installing, and I know the Python 3 install worked fine.

**Comment by lukas2511** [comment]
This is not a dehydrated issue but an issue with your hook script. You can set a shebang for python3.6 in your hook script.
