### ISSUE TITLE
HOOK_CHAIN="no" ineffective anymore?

### ISSUE THREAD

**Issue by v20z** [lukas2511/dehydrated#573]
Hello Gentlemen.

After upgrading from ver 0.4.0 to 0.6.2 I've faced out that HOOK_CHAIN="no" changed behaviour. In past it performed challenges deploy/validation in loop one by one:
```
HOOK: deploy_challenge for
 + Responding to challenge for 
HOOK: clean_challenge for
 + Challenge is valid!
HOOK: deploy_challenge 
...
```
But as I noticed in newer version it is simply performs at first either batch or one by one but consecutive all challenges deployment. Then at next stage performs all challenges validation. And finaly ether at once or one by one challenges removal.

My setup is dependent on the original behavior of the HOOK_CHAIN="no" option, i.e. deploy/validation sequence for each domain/cert.

Have I to correct it myself as it was? Or may I expect clarifications and some additional setting for original behavior?

Thank You.

P.S.
If my setup is stupid or incorrectly based on misunderstanding but it made in past as documented at https://github.com/lukas2511/dehydrated/blob/master/docs/hook_chain.md

**Comment by lukas2511** [comment]
Please have a look at https://github.com/lukas2511/dehydrated/blob/master/docs/troubleshooting.md#dns-invalid-challenge-since-dehydrated-060--why-are-dns-challenges-deployed-first-and-verified-later
