### ISSUE TITLE
Multiple domains.txt files?

### ISSUE THREAD

**Issue by maartendeblock** [lukas2511/dehydrated#576]
Is it possible to have multiple domains.txt files on different locations?

**Comment by lukas2511** [comment]
Yea you can create multiple config files and set the path to your domain list in there, then you can run dehydrated with `--config /path/to/config/file` and it will use that config with the defined domain list.

There is no intended cli parameter to just set a different domains.txt, please see https://github.com/lukas2511/dehydrated/pull/463 for the reasoning behind that.

**Comment by mono1966** [comment]
(8
