### ISSUE TITLE
Resume reading domains.txt after failed validation

### ISSUE THREAD

**Issue by movd** [lukas2511/dehydrated#577]
Thanks for the great work! I have one small request: Currently the script exits after a single failed validation.

I auto generate my domains.txt - Sometimes I have domains in the file which are not yet setup in DNS (*DNS problem: NXDOMAIN looking up A for [...]*). Thus the Challenge validation fails. Would it be possible to add a switch to skip this failed validation and resume with the rest of the domains.txt file?

**Comment by txr13** [comment]
There is a switch for this: —keep-going

**Comment by movd** [comment]
Thanks really thought I've read trough all the parameters!
