### ISSUE TITLE
dehydrated will not replace staging CA certs with real certs, after staging CA removed from config

### ISSUE THREAD

**Issue by dave559** [lukas2511/dehydrated#580]
As part of the (scripted) process of setting up my webserver, I try to request LE certs using the staging CA, and only then try to request certs with the live CA if this is successful (in order to try to prevent any configuration mistakes from triggering rate limits).

I am using dehydrated 0.3.1 (as that's what comes with my distro) and therefore ACME v1.

Once I have my dehydrated configuration setup, I run `dehydrated -c`, and then once again after I have commented out the staging CA.

However, dehydrated seems to think that my existing cert has not yet expired and so does not renew it.

What would I need to do in order to let dehydrated know that I do genuinely need to request a new cert in this situation?

Thanks for any advice.

**Comment by lukas2511** [comment]
Dehydrated doesn't refresh your certificate because from its view it's a completely valid certificate.
You can use `--force` to force dehydrated to refresh all certificates.
