### ISSUE TITLE
Feature: config options per domain

### ISSUE THREAD

**Issue by damluk** [lukas2511/dehydrated#585]
Hi,

I would appreciate a possibility to override a key algorithm per domains.txt line. In general, this could work for other config options as well, and look like this:
```
dom1.tld sub1.dom1.tld sub2.dom1.tld
KEY_ALGO=secp384r1 dom2.tld sub.dom2.tld
dom3.tld
```
Config options should not pose ambiguity problems as an equal sign is not allowed in a domain.

Thank you

**Comment by bllfr0g** [comment]
There is already a way to do this.  See https://github.com/lukas2511/dehydrated/blob/master/docs/per-certificate-config.md

**Comment by lukas2511** [comment]
@damluk you can use special config files like @bllfr0g already mentioned.

Variables in domains.txt are not supported and are not planned.
Parsing your example might be easy, but other variables are a bit harder and I don't want to maintain yet another set of options that users might get confused with what works and how.

**Comment by damluk** [comment]
@bllfr0g, thx for the info!
