### ISSUE TITLE
Can't validate challenge in --force update mode

### ISSUE THREAD

**Issue by osnwt** [lukas2511/dehydrated#586]
Initial request goes well, certs are received. Restart with `-c --force` gives the following error:

```
 + Handling authorization for mail.*****.net
 + 1 pending challenge(s)
 + Deploying challenge tokens...
 + Responding to challenge for mail.*****.net authorization...
  + ERROR: An error occurred while sending post-request to http://mail.*****.net/.well-known/acme-challenge/cObz7GJQnfuChtfwBeqSSBL-_V1iPGQD4axGRsL403M (Status 301)
```

It seems that dehydrated tries to POST to my own server instead of ACME one. My own server uses redirect to HTTPS (that's why 301). It worked properly for initial request, doesn't work with `--force`. 

`--force` is the reason. if I start it without certificates and use `--force`, it will fail too.

Ubuntu 18.04 LTS maintained version.

```
Dehydrated version: 0.6.1
GIT-Revision: unknown

OS: Ubuntu 18.04.1 LTS
Used software:
 bash: 4.4.19(1)-release
 curl: curl 7.58.0
 awk: GNU Awk 4.1.4, API: 1.1 (GNU MPFR 4.0.1, GNU MP 6.1.2)
 sed: sed (GNU sed) 4.4
 mktemp: mktemp (GNU coreutils) 8.28
 grep: grep (GNU grep) 3.1
 diff: diff (GNU diffutils) 3.6
 openssl: OpenSSL 1.1.0g  2 Nov 2017
```

**Comment by lukas2511** [comment]
This issue was already fixed, you just need to update dehydrated to the newest version.

**Comment by osnwt** [comment]
Thank you.
In that case we need to ask maintainer of ubuntu packages to update as well.
I just checked again, it seems that the version installed from ubuntu package repository is still with that bug.
