### ISSUE TITLE
More than one hook script

### ISSUE THREAD

**Issue by puzich** [lukas2511/dehydrated#589]
Currently I use the hook to create dns-01 entries in powerdns. But it would be fine, to start a further script for internal server purposes, after updating the ssl certificates. Could this be possible?

**Comment by txr13** [comment]
Write a wrapper hook. Pass whatever hook functions you like to the existing hook (which can then remain unaltered), and overload the rest with whatever you want to customize.

**Comment by puzich** [comment]
Yes! Good idea! Thank you!
