### ISSUE TITLE
DNS problem: NXDOMAIN looking up TXT for _acme-challenge.

### ISSUE THREAD

**Issue by jodumont** [lukas2511/dehydrated#595]
Hi;

I know it's not related to dehydrated and/or the hooks but I miss understood something;

do I have to create the `TXT _acme-challenge.` ?
if yes where I found the `VALUE`
may I have a concrete example ?

Regards!

Jonathan

**Comment by txr13** [comment]
You need to create a TXT record of the form:

_acme-challenge.certificatedomain.tld.

For example, if my certificate name was “certify-me.example.org” my TXT record would be “_acme-challenge.certify-me.example.org.” The value of that record will be given by the ACME CA server.

**Comment by lukas2511** [comment]
You (or ideally a script) have to create a _acme-challenge.yourdomain.tld TXT-record. The value for that will be generated by the Let's Encrypt server and dehydrated will call a hook-script with those values so they can be deployed. You should have a look at the example hook script which has an example deployment using nsupdate, or you could have a look at the project wiki where you can find a big list of user-provided hook-scripts for a ton of DNS providers / APIs.
