### ISSUE TITLE
No hook for NSD

### ISSUE THREAD

**Issue by rnz** [lukas2511/dehydrated#599]
Hello!
Among the [scripts](https://github.com/lukas2511/dehydrated/wiki/Examples-for-DNS-01-hooks) there is no hook for [NSD ](https://www.nlnetlabs.nl/projects/nsd/about/)
May be someone interest to create hook for NSD?

**Comment by jobe1986** [comment]
As long as NSD supports RFC2136 dynamic DNS updates (which as far as I can see from googling it does) you should be able to just enable dynamic updates for your zone and use one of the nsupdate scripts. Though to do so you will need to install the appropriate nsupdate utility, usually found in bind utils.

Alternatively you can easily write your own hook script using a variety of scripting languages and appropriate DNS client libraries supporting RFC2136 updates.

**Comment by lukas2511** [comment]
Not a dehydrated bug. Hooks are user-contributed.
