### ISSUE TITLE
Please pass domains to startup_hook

### ISSUE THREAD

**Issue by bzed** [lukas2511/dehydrated#600]
Hi,

it would be great if you could pass all domains to the startup hook like it is done for the other hooks, or add an extra "validate_domains" hook. We need to check if all (customer) configured domains are avtually lvalid before trying to get certificates for them - right now its a script wrapped around dehydrated, but I'd prefer to be able to do this in a hook.

Thanks,

Bernd

**Comment by lukas2511** [comment]
Sorry, but I think that you should really validate the customer domains before handing them over to dehydrated.
The way `startup_hook` currently is implemented there is no way of adding the domains to it and your only move would be to cancel execution anyways, so it's not much better than a wrapper-script, actually even worse as with a wrapper you can use the `--domain` parameters and do your domain-list-parsing the way you need it.

Also you could set the `KEEP_GOING` parameter and dehydrated would just continue with the next certificate if there is an issue with domain validation.
