### ISSUE TITLE
Command '--cron' meaning

### ISSUE THREAD

**Issue by nlevchuk** [lukas2511/dehydrated#603]
Hello. First of all thanks a lot for you script. It's really helpful.

I confused with meaning '--cron' command. At first glance i thought if i call the script with '--cron' command it should create crontab task. But it didn't do that.

Can you explain meaning of '--cron' key ?

**Comment by jobe1986** [comment]
The purpose of the --cron flag is to be passed as a flag when running dehydrated from crontab. For example in a crontab you would put something like:
`7 10,22 * * * /home/jobe1986/dehydrated/dehydrated --cron >/dev/null 2>&1`

Or if you wish to receive the output of dehydrated as an email then you could use:
```
MAILTO="jobe1986@example.com"
7 10,22 * * * /home/mbeeching/dehydrated/dehydrated --cron
```

**Comment by nlevchuk** [comment]
But it's not understandable. And it's problem. Not for script execution, but for UI.

- What does this  `/home/jobe1986/dehydrated/dehydrated --cron` command do?
- It checks if certificate has expired. If so, it will update him. Otherwise, nothing.

That's all! There is no action with cron.

There is more understandable name for that. For example, --update-certs.

The `--cron` key should only add the script to crontab and nothing more.

If need to check and update right now plus add to crontab it should look something like this:

```
/home/jobe1986/dehydrated/dehydrated --update-certs --cron
```

What do you think?

**Comment by bllfr0g** [comment]
It’s called  --cron because it’s the flag you use when calling dehydrated from a crontab. 

I agree it’s not the naming I would have chosen, but that’s what it is.

**Comment by nlevchuk** [comment]
But use `--update-certs` or something like this much better and understandable. @lukas2511 what do you think? Maybe it's time to change? )

**Comment by txr13** [comment]
I think it’s perfectly understandable if one reads the readme / help output. You’re using the flag to select cron mode, not to output to crontab.

**Comment by nlevchuk** [comment]
@txr13 if it's like a mode of operation than it should call appropriately - `-m, --mode NAME`
```
--mode cron
--mode signCSR
```

it's more intuitively. But using `cron` command and don't do for cron anything it's strange :)

**Comment by lukas2511** [comment]
I agree that the name might not be the best, but that's what we got now.

The tool was designed to basically do everything fully automatically, being called by a cron daemon, that's where the name of the switch comes from.

I'm not going to change it as it would result in a lot more trouble than telling the two people who didn't read the `--help` text what it does.
Adding additional commands would only end up in a lot more confusion.
