### ISSUE TITLE
"No such file or directory" when generating certificates 

### ISSUE THREAD

**Issue by ianhyzy** [lukas2511/dehydrated#608]
I'm trying to use this script on a Synology NAS and got stuck at this point. I have the config file in the folder I'm running the script in, it prints the correct path but then fails. It worked fine with the setup command.
![image](https://user-images.githubusercontent.com/3400872/48990863-e259f480-f0f5-11e8-9498-6cf6e282062c.png)

**Comment by txr13** [comment]
I think the Synology uses ash as the default shell, rather than bash? In any case, please run the following command and post the output (substitute bash or whatever other shell you're using, as necessary):

`ash -x /volume1/Vault/configs/ssl/dehydrated -c`

**Comment by ianhyzy** [comment]
The output was quite long so I put it in a gist here: [https://gist.github.com/ianhyzy/f4be7bfb7423554e0651ec7a30985082](url)

**Comment by txr13** [comment]
It's looking for your hook script at `/volume1/Vault/configs/ssl/hook.sh` and not finding it.

**Comment by ianhyzy** [comment]
It is there, are the permissions wrong?
![image](https://user-images.githubusercontent.com/3400872/49024918-24b81b80-f160-11e8-86b2-d7775f3451db.png)

**Comment by txr13** [comment]
There are a couple of possibilities for this error. It could be an incorrect shebang line in the hook. There have also been reports of DOS line endings causing the same error message.

**Comment by ianhyzy** [comment]
The Windows line endings were the culprit. There's no `systemctl` on the machine though (`sudo: systemctl: command not found`). Is there a way to use /etc/init [like HASS does](https://www.home-assistant.io/docs/autostart/synology/)? Thanks for the help as well.

**Comment by txr13** [comment]
I'm sorry, I don't understand. There's no requirement for systemctl within dehydrated. What are you trying to accomplish?

**Comment by ianhyzy** [comment]
To clarify, I'm getting that error when the script runs. It prompts me for a password and then fails: 
![image](https://user-images.githubusercontent.com/3400872/49029630-aca32300-f16a-11e8-93fb-775f10f7f13d.png)

**Comment by txr13** [comment]
OK, that's in your hook script.  (Not a dehydrated issue.)

At a guess, though, I'd say you can just customize your hook script to use whatever facilities exist in your environment. I'm not familiar with a Synology environment, so I'm afraid there's not much I can offer in specific.

**Comment by ianhyzy** [comment]
Ah alright, I copied that from [here](https://www.splitbrain.org/blog/2017-08/10-homeassistant_duckdns_letsencrypt). Thanks for the help!
