### ISSUE TITLE
Does dehydrated support TLSA record generation?

### ISSUE THREAD

**Issue by andreasschulze** [lukas2511/dehydrated#615]
When using ACME to issue certificates for Mailservers, one may want to publish TLSA-Records too.
The general timeline would be:
 - generate a new private key + req
 - issue new cert
 - calculate the TLSA-Record data (TLSA Mode 3 3 1)
 - put these data into DNS
 - make sure, the published TLSA Record data are globally visible
 - wait at least the TLSA Record's TTL so old data will expired
 - deploy the new cert

Is there a suggested way to implement a similar behaviour with the current version (0.6.2) ?

**Comment by txr13** [comment]
Seems this would be better implemented in a hook script’s deploy_cert function.

**Comment by jobe1986** [comment]
The following site gives a little useful info on using openssl commands to generate the values for TLSA records (for the public key only) but that alone should give you hints on what to do for the full certs too:
https://blog.tyk.nu/blog/generating-tlsa-records-with-openssl/

**Comment by lukas2511** [comment]
I also think this doesn't belong directly into dehydrated, but rather into an external hook-script. Thanks for the idea anyway.
