### ISSUE TITLE
Implement POST-as-GET

### ISSUE THREAD

**Issue by aloopkin** [lukas2511/dehydrated#626]
Please implement POST-as-GET (draft 17+):

https://community.letsencrypt.org/t/acme-v2-scheduled-deprecation-of-unauthenticated-resource-gets/74380

**Comment by lukas2511** [comment]
Already on my todo 👍 (https://github.com/lukas2511/dehydrated/issues/510#issuecomment-431571523)

Keeping this open as a reminder.
