### ISSUE TITLE
Failure reported by nsupdate. Bailing out!

### ISSUE THREAD

**Issue by wprauchholz** [lukas2511/dehydrated#627]
I run CENTOS 7 homerserver. Trying to obtain a certificate for wildcard domain. The process fails with error message :Failure reported by nsupdate. Bailing out!:

I added in the config file CHALLENGETYPE="dns-01" and HOOK="${SCRIPTDIR}/hook/hook.sh"
In the file hook.sh I set
[ -z "${NSUPDATE}" ] && NSUPDATE="/usr/bin/nsupdate -k /run/named/session.key"
[ -z "${SERVER}" ] && SERVER="<mydomain.com" (I also tried the IP address and www.<mydomain.com> too.

Any help is very welcome

Thanks you, Wolfgang

**Comment by lukas2511** [comment]
I'm not sure you understand how nsupdate is supposed to work, it connects to your primary nameserver and updates your zone.

You have to have the correct key to access the primary nameserver for your domain and you have to define your primary nameserver for nsupdate so it knows where to connect to.
