### ISSUE TITLE
tls-alpn-01 - urn:ietf:params:acme:error:unauthorized Status 403

### ISSUE THREAD

**Issue by tootai** [lukas2511/dehydrated#628]
Hello,
I receive following error using tls-alpn-01:
[...]
 + Generating ALPN certificate and key for <myhostname>...                                    
 + 1 pending challenge(s)                                                               
 + Deploying challenge tokens...                                     
 + Responding to challenge for <myhostname> authorization...
 + Cleaning challenge tokens...                                                                                        
 + Challenge validation has failed :(                               
ERROR: Challenge is invalid! (returned: invalid) (result: {
  "type": "tls-alpn-01",                                
  "status": "invalid",                                            
  "error": {                                                   
    "type": "urn:ietf:params:acme:error:unauthorized",                 
    "detail": "Cannot negotiate ALPN protocol \"acme-tls/1\" for tls-alpn-01 challenge", 
    "status": 403                                                
  },                                                                                     
  "url": "https://acme-v02.api.letsencrypt.org/acme/challenge/wVQElJRFux4QSGXX6sqB37wOG9BXWFVffc1Hcgejx3U/11594171888",    
  "token": "Wkw6buVxdR3bd41jyeNGUjdG-crPgAG4PltzC9Bq1PU",                                                                                                                     
  "validationRecord": [                         
    {                                                     
      "hostname": "<myhostname>",                
      "port": "443",                                         
      "addressesResolved": [                                                                    
        "ipv4 address",                                                  
        "ipv6 address"                                                            
      ],                                                                                                               
      "addressUsed": "ipv6 address"                                               
    }                                                                  
  ]                                                                                       
}) 

Thanks for any hint.

Daniel

**Comment by lukas2511** [comment]
Well, it seems like you didn't configure tls-alpn at all, your webserver doesn't handle that protocol, so it doesn't work.
