### ISSUE TITLE
Strange response from Challenge Validation (403)

### ISSUE THREAD

**Issue by jillian1701** [lukas2511/dehydrated#634]
Hello. I'm trying to set up dehydrated and I'm getting a strange Challenge Validation error:

```
ERROR: Challenge is invalid! (returned: invalid) (result: {
  "type": "tls-alpn-01",
  "status": "invalid",
  "error": {
    "type": "urn:ietf:params:acme:error:unauthorized",
    "detail": "Incorrect validation certificate for tls-alpn-01 challenge. Requested mysitename.us from x.x.x.x:443. Received 1 certificate(s), first certificate had names \"kubuntu\"",
    "status": 403
  },
```

I'm unsure why it returns "Kubuntu". I do run kubuntu, so it seems logical to assume I've set something up incorrectly. However, this was all working using CertBot. 

Any ideas what might be going wrong?

**Comment by txr13** [comment]
Are you sure you want to be using the tls-alpn-01 challenge type? This requires a very particular and uncommon configuration to validate, and it's very infrequently seen.

**Comment by jillian1701** [comment]
@txr13 My ISP blocks port 80 entirely, there is no way to open it up. I'm under the impression that tls-alpn-01 is my only option?

**Comment by txr13** [comment]
You have two options, in this case: dns-01 and tls-alpn-01. While I'm more familiar with dns-01 challenges (and they also permit wildcard validations), that requires additional configuration as well, so it may not be optimal for your use case either.

I've never used tls-alpn-01, but I can (somewhat) read the code involved. Can you provide more information on your configuration (particularly what you have set as `ALPNCERTDIR`, what responder you're using, and the responder's configuration)?

**Comment by jillian1701** [comment]
Yes!! Thank you @txr13! It was ALPNCERTDIR. I still had that set the default, which was I needed to change. All is working well now. You're the best!

PS - I'm using the instructions found [here:](https://medium.com/@decrocksam/deploying-lets-encrypt-certificates-using-tls-alpn-01-https-18b9b1e05edf), so I'm using alpn-responder.py as a responder.

**Comment by txr13** [comment]
I thought you might be using that source for instructions. While I would change some of those instructions if I had been the one writing it, and while it really doesn't explain how `dehydrated` does what it does (or why the various options are important), it seems serviceable enough. Glad you got it working! 

I'll just leave you with a couple of thoughts for future: be aware that installing `dehydrated` using those instructions will not keep the script updated automatically. As bugs are fixed, or as the ACME standard evolves, you may eventually find that your script no longer functions correctly. Also, if you're ever asked to provide the version number, the built-in version command will give a result which doesn't make sense. (It will say that you're using "git-master-after-0.6.2", but with a git revision of "unknown".) There will be no way to identify exactly which revision you're using, and it will consequently be more difficult to troubleshoot things for you, if you run into a bug in the script itself.

**Comment by jillian1701** [comment]
Thanks again, @txr13! Is there a more appropriate set of instructions with a more robust explaination that I could use? 

Likewise, is there a better method of installing dehydrated? I do plan to automate this process using a script of some sort. First up was getting things running again! :)

**Comment by txr13** [comment]
For installation, I would recommend one of two different methods, depending on your needs.

The first option is to simply install from the Ubuntu "universe" repository. I don't know what version you're using, but I can see that Bionic (18.04) is using 0.6.1 (with an additional patch cherry-picked from the 0.6.2 release). Cosmic (18.10) is on 0.6.2 directly. Installing `dehydrated` from the Ubuntu package repository means that the script will automatically update as the package is updated in future, but won't be bleeding-edge--you'd need to wait for updates to be released by Debian, and then pulled in by Ubuntu. Even so, this is the route I would suggest for most non-technical users.

The second option is to install `dehydrated` by using git to clone the GitHub repository. Full instructions for doing so are probably out of scope for this particular issue, but going this route means that you get the absolute latest version of `dehydrated` and all its documentation. It does not automatically update on its own, but you can update it at any time by pulling in any new changes from GitHub, including any bug fixes that get patched.

In truth, I would highly recommend looking through the GitHub repository anyway. There's a lot of documentation available (see https://github.com/lukas2511/dehydrated/tree/master/docs). I would also go through the README (https://github.com/lukas2511/dehydrated/blob/master/README.md), particularly the Usage section. (For example, while the Medium post uses the `-f config` parameter when executing `dehydrated`, that parameter isn't actually needed, assuming you don't have another config file present in a higher-priority location.)

**Comment by jillian1701** [comment]
Thank you for the recommendation. I think I'll go the github route. :)

**Comment by lukas2511** [comment]
Closing this as this seems resolved. Thanks @txr13! I'm going to release a new version of dehydrated with all the latest changes very soon, hopefully this will land quickly in the external repositories...
