### ISSUE TITLE
dehydrated for python?

### ISSUE THREAD

**Issue by Tungsteno74** [lukas2511/dehydrated#641]
Hello Lukas,
probably not the right place, but I don't know where else to ask:
Is there a Python version of "dehydrated"?
I ask this because I'd like to use this script in a Python module without calling it externally with popen or subprocess.

A quick google search did not lead to a positive result, so thanks in advance for your reply.

**Comment by cpu** [comment]
> I ask this because I'd like to use this script in a Python module without calling it externally with popen or subprocess.

Have you considered Certbot's `acme` module? It isn't the most straight-forward API but you would be able to accomplish your goal with pure Python code (without needing the full Certbot): https://pypi.org/project/acme/

**Comment by Tungsteno74** [comment]
hello @cpu, thanks for your reply.
I didn't go deeply on the certbot documentation , but reading the readme indicates that:
"In most cases, you need **root or administrator access** to your web server to run Certbot."
and this would be a problem for me. 
For this reason I would like to use the _dehydrated_ implementation, which from what I read in the following guide https://www.splitbrain.org/blog/2017-08/10-homeassistant_duckdns_letsencrypt does not need _root/sudo_  access to request certificate or update it ( feel free to correct me about what i said).

**Comment by cpu** [comment]
@Tungsteno74 for what its worth that applies to running Certbot (which can also be configured to run without root), and isn't particularly germane to using the `acme` module programmatically. It sounds like you're keen to stick with Dehydrated so I'll bow out and let the maintainers respond. Good luck!

**Comment by lukas2511** [comment]
Yea, if you need something python...y you may want to use the acme module. If you only need to trigger dehydrated from python you could easily use the subprocess module and just call dehydrated.
