### ISSUE TITLE
wildcard *.domain.name not send to hook

### ISSUE THREAD

**Issue by rnz** [lukas2511/dehydrated#644]
In hook domain.txt:
domain.name *.domain.name > cert_domain.name

but hook run twice domain_challenge with: domain.name

```
...
case "$1" in
    "deploy_challenge")
        echo "domain: $2"
...
```

**Comment by jobe1986** [comment]
Wild card domain validation is performed on the domain name WITHOUT the wild card specified. So if you are validating "*.domain.name" then the deploy_challenge hook will be instructed to deploy a challenge for "domain.name". In your example this will appear initially as an attempt to deploy a challenge for "domain.name" twice, once for "domain.name" and once for "*.domain.name"

**Comment by lukas2511** [comment]
Like @jobe1986 said wildcard domains are validated using the upper level domain. If you need information about what domains your hook is validating you can use the altnames variable.
