### ISSUE TITLE
A simple question on dns txt variable

### ISSUE THREAD

**Issue by Tungsteno74** [lukas2511/dehydrated#645]
Hello @lukas2511 ,

I can't find at which dehydrated code the `$4` variablie in the [duckdns hook.sh](https://github.com/lukas2511/dehydrated/wiki/DNS-01-hook-for-DuckDNS) refers.

This is the piece of code: 
```
    "deploy_challenge")
        curl "https://www.duckdns.org/update?domains=$domain&token=$token&txt=$4"
        echo
        ;;
```

It is supposed to be a TXT with record APIs from [duckDNS page](https://www.duckdns.org/spec.jsp), but which ones exactly?

I ask this because I'm trying to implement another Hook based on this.
Thanks in advance

**Comment by jobe1986** [comment]
It should be noted that when comparing the linked duckDNS hook script to the example hook script https://github.com/lukas2511/dehydrated/blob/master/docs/examples/hook.sh that the $<number> variables are offset by one. That is where the duckDNS hook script says $4, read that as $3 in the example hook script. So in this case, $4 is the token value and thus the content of the TXT record.

**Comment by Tungsteno74** [comment]
thanks @jobe1986 ,
ok well, now i understand better why how works, but why is it shifted?

Practically, the following slice of code from dehydrated hook.sh example is wrong:
```
deploy_challenge() {
    local DOMAIN="${1}" TOKEN_FILENAME="${2}" TOKEN_VALUE="${3}"
```
I tested it and DOMAIN variable give me "deploy_challenge" value. As you proposed if i "shift" it by one it returns me the correct value.
Is this a normal behavior or i miss something?

thanks

**Comment by lukas2511** [comment]
The example hook shifts the variables before calling the functions (see last few lines of that example script). So yea, problem seems to be that you copied stuff around without adjusting for the differences in the scripts.
