### ISSUE TITLE
unbound variable

### ISSUE THREAD

**Issue by n3gativ3** [lukas2511/dehydrated#654]
Hello. 
Pull new version and get error when tried generate certs:
/opt/dehydrated/dehydrated: line 408: CA_NEW_ACCOUNT: unbound variable
It`s fresh update in change log.

**Comment by n3gativ3** [comment]
Change acme api to v2 from v1 and it`s work now. 
Tried on another fresh server with v1 and it works too.
It`s strange

**Comment by lukas2511** [comment]
Yea, seems I've broken v1 compatibility with the critical patch yesterday. Damn... I just pushed a new version, can you test if that works fine?

**Comment by n3gativ3** [comment]
Yeah, sure. Few min and i give response.

**Comment by n3gativ3** [comment]
I've already tested fix and  all work fine. Template generate certs from ansible and puppet works too.
Thanks you. You do  great things.
