### ISSUE TITLE
Using domain alias

### ISSUE THREAD

**Issue by astorath** [lukas2511/dehydrated#657]
Hi!

How can I use domain/challenge alias with dehydrated? Have found nothing in docs about that...

**Comment by jobe1986** [comment]
Could you elaborate as to what you mean by domain/challenge alias?

The reason I ask is the terminology you used can have multiple different meanings.

Either way, if you mean CNAME records, then yes Let's Encrypt's dns-01 validation will follow CNAME records. I for example use _acme-challenge.<domain> CNAME'ed to _acme-challenge.<domain>.<dynamicdnsdomain> so I keep all my dynamic DNS under a single domain name.

**Comment by astorath** [comment]
@jobe1986, yep, I mean CNAME records.

How do you setup dehydrated then? Where should I put alias domain (the one dehydrated will use to setup challenges)?

**Comment by jobe1986** [comment]
That would have to be accounted for by your custom hook script that handles the dynamic DNS updates, as to how exactly that really depends on which hook script you use, and I only have experience using the basic nsupdate based hook script.

**Comment by astorath** [comment]
I see, thanks
