### ISSUE TITLE
Strato Support?

### ISSUE THREAD

**Issue by leonlatsch** [lukas2511/dehydrated#661]
Will there be any support for [Strato](https://strato.de)?

**Comment by lukas2511** [comment]
What exactly do you mean?

**Comment by leonlatsch** [comment]
I can't find Strato in [this](https://github.com/lukas2511/dehydrated/wiki/Examples-for-DNS-01-hooks) Document. Is it supported?

I need to renew my LetsEncrypt wildcard certificate with dns-01 challange.

**Comment by txr13** [comment]
Dehydrated doesn’t technically “support” any of those providers in that document. Any compliant hook script will work with dehydrated; the hook scripts listed are examples.

I don’t know if there is a hook script out there which supports Strato in a fully-automated fashion. I suspect that largely depends on what sort of API access they offer. Even failing that, you could use a semi-automated hook like email-notify-hook or manual-dns-hook and do the record updating yourself. But those would be outside of dehydrated’s scope.

**Comment by lukas2511** [comment]
As @txr13 said you would need (to write) a compatible hook script. Those are handled outside of the scope of dehydrated itself as there are thousands of options and I don't want to maintain all of them.
