### ISSUE TITLE
Please add option --reuse-key

### ISSUE THREAD

**Issue by msebald** [lukas2511/dehydrated#676]
Is it possible to add the --reuse-key option? I am looking into this right now because of DANE TLSA records, see here: https://community.letsencrypt.org/t/please-avoid-3-0-1-and-3-0-2-dane-tlsa-records-with-le-certificates/7022/17

**Comment by txr13** [comment]
You can set the option `PRIVATE_KEY_RENEW="no"` in your config file. If you don't want that to be a global default, you can also set this option in a per-certificate config file.

**Comment by msebald** [comment]
Great, thank you very much. I just set this option in my config files. Scripts still work, but it will take some days until some certs expire. But I'm closing this issue right now, I am sure it works. :-)
