### ISSUE TITLE
cURL error 35, recent random failures to connect to LE

### ISSUE THREAD

**Issue by davidearl** [lukas2511/dehydrated#680]
Any thoughts on this: https://community.letsencrypt.org/t/curl-error-35-random-failures-to-connect-to-le/103355 ?

**Comment by futureweb** [comment]
@davidearl - see Let's Encrypt Status Page ... Active Incident about those Errors: https://letsencrypt.status.io/

Additional Infos: 
- https://community.letsencrypt.org/t/curl-tcp-connection-reset-by-peer/103149
- https://community.letsencrypt.org/t/curl-error-to-directory-endpoint/103027
