### ISSUE TITLE
Option to specify own Root CA

### ISSUE THREAD

**Issue by kbabioch** [lukas2511/dehydrated#683]
dehydrated will use curl for interaction with the ACME server. This will, by default, use the system store. There seems to be no option to specify the root certificate for the ACME server. This is a problem when running a private ACME implementation and not using the official Let's Encrypt one.

I could work around this by specifying `CURL_OPTS` for now (`-k` for instance), but it should be possible to do this via a command line parameter, i.e. something like (`--root-ca`).

**Comment by lukas2511** [comment]
Why not just set `--cacert ca.crt` as curl opts in config? If you are using a custom CA you probably have a config file already anyways? I don't really see the point of adding it as a cli parameter, or am I missing something here? Going to close this as this already seems resolved to me.
