### ISSUE TITLE
How to change from ACME v1 to ACME v2?

### ISSUE THREAD

**Issue by dave559** [lukas2511/dehydrated#692]
I got bitten by recent LetsEncrypt changes the other day (resulting in the #684 error), on a couple of servers running Debian 9 (and therefore a rather old version of dehydrated), which we can't update to Debian 10 yet as we are running long term support web apps which don't yet support PHP 7.3.

I was able to work around this by manually installing the latest dehydrated directly from the git repo, but I am aware that another issue that I now have to plan for is the [End of Life for ACME v1](https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430).

What do I need to do to switch my dehydrated setup from ACME v1 to ACME v2? 

Is it just a case of updating the **CA** definition in the [config](https://github.com/lukas2511/dehydrated/blob/master/docs/examples/config) file, or is there anything else that I need to do?

**Comment by denisinvader** [comment]
Changing CA to `...-02...` worked for me

**Comment by lukas2511** [comment]
Yup, just change the url to the ACME v2 endpoint, dehydrated will automatically migrate your account. In case that fails just move your accounts directory and run `dehydrated --register` to create a new account, from there everything should work as normally.
