### ISSUE TITLE
01070277:3: The requested key (domain.com_2019-12-27.key) was not found.

### ISSUE THREAD

**Issue by devpets** [lukas2511/dehydrated#699]
working with version F5 14.1.2
using latest dehydrated version.
just after running the first time the first domain throws an error, in the client ssl profile it uses the default key/cert pair, it successfully creates the CRT/KEY but doesnt attach them to the profile.
This is the error:
01070277:3: The requested key (domain.com_2019-12-27.key) was not found.

looks like the key created on F5 without the .key extension, maybe this is the reason for the error?

**Comment by lukas2511** [comment]
You'll have to contact F5 support for this. They are just using my software, I have no idea how they integrated it into their system.
