### ISSUE TITLE
Challenge validation over https link

### ISSUE THREAD

**Issue by Jancs-E** [lukas2511/dehydrated#701]
Hi!
I already have https server running and wanted to have the challenge validation happening using it, but I got an error showing that the challenge verification happened using regular http link.

Is it possible to switch it over or I have to create the dummy http host just for verification?

**Comment by jobe1986** [comment]
When using http-01 Let's Encrypt will always try http:// instead of https://, however they will automatically follow redirects to https:// so if you create a dummy vhost it will only need to redirect to https://

**Comment by Jancs-E** [comment]
Citēts Matthew Beeching <notifications@github.com>
Fri, 03 Jan 2020 23:52:31 -0800:

> When using http-01 Let's Encrypt will always try http:// instead of  
> https://, however they will automatically follow redirects to  
> https:// so if you create a dummy vhost it will only need to  
> redirect to https://

unfortunately it is not the option in some cases - when both http and  
https are used on the same server
-- 
ph. +37129203061

http://dict.dv.lv

**Comment by lukas2511** [comment]
Unfortunately http-01 doesn't allow for anything else but access using http://. If you need validation on port 443 you'll need to use tls-alpn-01 which is a lot more complicated to set up. There is a bit of example config + code in the docs directory, but since there are tons of options for this it's hard to explain for every possible configuration.

**Comment by Jancs-E** [comment]
Citēts Lukas Schauer <notifications@github.com>
Sat, 04 Jan 2020 08:12:15 -0800:

> Unfortunately http-01 doesn't allow for anything else but access  
> using http://. If you need validation on port 443 you'll need to use  
> tls-alpn-01 which is a lot more complicated to set up. There is a  
> bit of example config + code in the docs directory, but since there  
> are tons of options for this it's hard to explain for every possible  
> configuration.

Thank you, I will look into tls-alpn-01

Janis
-- 
ph. +37129203061

http://dict.dv.lv
