### ISSUE TITLE
how do i make sure i use acme-v2?

### ISSUE THREAD

**Issue by toastbrotch** [lukas2511/dehydrated#705]
i just now received an email from LE that i use v1, which is going to fade out. i have the latest code version, but also a very old config file:

CA="https://acme-v01.api.letsencrypt.org/directory"
LICENSE="https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf"
CHALLENGETYPE="http-01"
BASEDIR=$SCRIPTDIR
DOMAINS_TXT="${BASEDIR}/domains.txt"
CERTDIR="${BASEDIR}/certs"
ACCOUNTDIR="${BASEDIR}/accounts"
WELLKNOWN="/var/www/dehydrated"
KEYSIZE="4096"
HOOK=${BASEDIR}/hook.sh
RENEW_DAYS="30"
PRIVATE_KEY_RENEW="yes"
KEY_ALGO=rsa
CONTACT_EMAIL=foo@bar.com
LOCKFILE="${BASEDIR}/lock"
OCSP_MUST_STAPLE="no"

is it the CA config? i commented it out, but output looks the same... how do i make sure i use acme-v2?
thanx and cheers.ivo

**Comment by toastbrotch** [comment]
seems CA is not needed at all, but not sure if this is the only "switch" to v2...

**Comment by jobe1986** [comment]
If you take a look at the example config file you will see the CA setting for the "acme-v02" CA:
https://github.com/lukas2511/dehydrated/blob/master/docs/examples/config#L25

**Comment by toastbrotch** [comment]
ok, when its only this config, i've just switched to v2. thanx
